- name: set resolv.conf
  template:
    src: resolv.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: set dhcpcd.conf
  template:
    src: dhcpcd.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload dhcpcd