ansible_user: michael
ansible_become_pass: ENC[AES256_GCM,data:rs5lMftt6naD5mpl5QAe55wYoOeoVK1cUA==,iv:YwR86AR5pjXoumfE6bh/Vl9oBPGP+OVNskO9LBGt/S0=,tag:EtjZaLhIBiYMljxvulpf0g==,type:str]
flannel_iface: ens18
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'
extra_args: --flannel-iface={{ flannel_iface }} --node-ip={{ k3s_node_ip }}
extra_agent_args: '{{ extra_args }} --kubelet-arg=allowed-unsafe-sysctls=net.ipv4.conf.all.src_valid_mark --node-taint vm=true:NoSchedule'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-20T22:15:32Z"
    mac: ENC[AES256_GCM,data:anjcLOhzVVl5ZJyIb44oXGoFMA8Qvoha89rrp769TSUlkgfucHKSvHOrfqnxtczzKL2CKekb/ILiamwOgjMjgrqTZBc1V/uxS99V4aqtbF76n9T94tFl6Bjfcd/YHp/Oy4JD+1P6TDBXZkUsVCEKHVXqvsRwFHUeH8B3/Ka/4u0=,iv:EF5fRxz0cWwMJ+xAaGSHdr+gNfY4O6We3Tj0FP3SAgI=,tag:JeieW6Is1JWywYLZ4uOeiQ==,type:str]
    pgp:
        - created_at: "2025-04-20T22:15:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDAQ/+IhoqqThUexoaPbAx6UNPD+Fx9/D4fazsk5HZsSy73w1h
            pclS7pq/IsVTER7eqKjzpXhGazDEjoyneU2Ac97A/TfMxtzZcVRkTDA4eWFBeTV/
            3n5eMkel13xvJ1pi7zV4VuxduyPvcFuLB/xks7zrTBxj8isJIJV2/DhD2O1hWkdH
            NHljkY4WTmidv5aUaF3SKLMtRBI89cEcSpR4KV8a8gRolBcpCP/h9WP0bgm/GNlV
            5p9scUhsrlAvZIZEu3xL4wYeOsaCe87MW80Kq/u+aB0AcRi9aVm+FdknIS74CkZw
            hNm1pKoqvJE1bw8mNQ77krl+QiYPS1JENoFvOE+tPsvbUof4qBJETXwfaVO88V8H
            +lxTUbuaQ2rpwXplpJEZRRvnW/+IYDD3xHMDgx3qfQuG1i16gmf62QaZxbUWw2yu
            o2HawIfM482QItc8yGH0lnzDs6Ji59pI1nUuKWWP70XZ6j4Tz1IVqQJ6S1Wd2n99
            pYLaSMfU83Wkv0mNiIQ/nxpPQYtKq4otOV/3EKg0W4pT609dYUNvB/jo3jh+dofD
            Tux4vvgGyWvp35EdRqyfc1WGp/8hQSqrKl8sm9Ud2gTUe7Z4yvzziSsyDeq2quXW
            CYh1yGW4d/IYpMgqUeZs6QREWyji/S8RlLkFoGHIiuwJ9CSpcsGwRk1GiuWU9ojU
            aAEJAhDWnVq0QTtK2Pv9WgG+nYAg5lxlFXCoroLy1PyrVD+b1+LVHkfNERn60mI6
            REdeRvHXG3/0Lb7sOlUPtE7qkejuOmywgcPWfuTjkBylTFQV51Ajkd7bWylEj2WV
            Sc6r4yvrKShD
            =PkwD
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(k3s_token|ansible_become_pass)$
    version: 3.8.0
