ansible_user: michael
ansible_become_pass: ENC[AES256_GCM,data:rs5lMftt6naD5mpl5QAe55wYoOeoVK1cUA==,iv:YwR86AR5pjXoumfE6bh/Vl9oBPGP+OVNskO9LBGt/S0=,tag:EtjZaLhIBiYMljxvulpf0g==,type:str]
flannel_iface: ens18
k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'
extra_args: --flannel-iface={{ flannel_iface }} --node-ip={{ k3s_node_ip }}
extra_agent_args: '{{ extra_args }} --kubelet-arg=allowed-unsafe-sysctls=net.ipv4.conf.all.src_valid_mark --kubelet-arg=feature-gates=SidecarContainers=true --node-label vm=true'
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDajFRVUVuOVl0YmJRdnRR
            Smw2Q0NnY2hhdTBOOTMrMXFNK05NR09Lbm5VCkZOTW9Wa1Z6cU9sNS9CeUJMSzJU
            MFRpa0VqUWRHQis1WXE0NGlMQ0YxeUUKLS0tIHZsTDJ2cDdMVGRqZ2VPV3QzdDFS
            TGZEUHRnNy9UY0syUFJBRzRzUmRHN2sKuec5glxUrEntZN7slXDsYJSAoSH+FXHe
            yBjQYsqOpvAKkQ45L2YIrxmT0KWckmovic5NR10OXlZUFrPazoSQNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T15:59:16Z"
    mac: ENC[AES256_GCM,data:piqhiiT2UymOfNbwX4FHe1iqsp2puujxJ7vbE41C7WG6EOrT4F9UvHxKaCCQsziVoif9rzZwgqB4F6XW5OfHOEWUvFyGVi9N/ntqE6Sf6NS9bulHMacoCpFt0UjmtqvWbmS3k6vuomneh7TPOeUztyx38ohe7yaH8wMfEI0A/c4=,iv:MgjALQqCgS9g9Bc1RlOggj0MBfQqMn6AEnmu7G4Nyis=,tag:9Jm2HLcbxpCHDZtF47hBYw==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ//X3wshv2ii4DSQtehQE61zUCLINIiOwcMQajX2sh9ZBu5
            U0UUHRDN9OqxyUDurb6gV0/pIV65x/uQvMPymQvcb+4YP/WqyY9POua3UiAqt0Hc
            shrA8+IMYs98RO6GlPccKmSh2jCRBXw54HWie3cOpsTSBFwbti33iJiSqDZM6K7M
            1xXGxA9NTxXsmGYvjU9XXMWrmVXCAvQUI8Xx2fTtXN5jZSLiQ/tN8eoJJV4TljYO
            frEjYisuEASDK+QJRiS5tFwliwtPvM7dcf7Jy8OXeGYBfguO+wbVOUwKYcEhASCP
            lWbffLyrMyX9SLh/TyXZM2U6bQ7UDFM64Cid8eVjoOcFzdr8bQXLuW0U7m84EffA
            405SxQ+Qlyr4UvEKzKnCOaR2eDZU9OHPDNIHQGmfpTTrZeVM2CTN2Gi3bCuljKWu
            DuPclcobaWrQX3L48NUBCh9qwEaSIipESSIcLtdjQ5wRepxOTS4IM+bre5dgdDyE
            s5nXo/JNbBopajZJk7OdVD9jVF+SBHesTCURcoj8FzU4aqVy4EwBPSxQJixWi3gL
            Ai4gl1+zoksYRlJ7QSLQbMVQBzI9YzV3ZPtGxuLCJBtGgXDc7gppc9tkzpAThYrQ
            ThxSIOv1qTwB99Aj9V7MN6JpUoscUYjl9vgbcgJTw4+90Zc9z8qYT04QG9aD4gDU
            aAEJAhA9VqBFwYTkUMp8soXh9UoVn8Ujckthl/Q72nVz5Cqd3CTfpPiQCZbfGNyH
            PbxZozYUpA47/FDfufJeJU5WDWz6HqSXLalOf87WqWyu5CcsWmLATaSnRQYAwRIa
            VwfpGrBucdg5
            =BQ/V
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(k3s_token|ansible_become_pass)$
    version: 3.8.0
