---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  namespace: home
  labels:
    app: sabnzbd
spec:
  serviceName: sabnzbd
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      name: sabnzbd
      namespace: home
      labels:
        app: sabnzbd
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: vm
                    operator: In
                    values:
                      - "true"
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:5.0.3
          ports:
            - containerPort: 8080
              name: sabnzbd-port
          envFrom:
            - configMapRef:
                name: common-configs
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "4096Mi"
              cpu: "3000m"
          volumeMounts:
            - name: sabnzbd-configs
              mountPath: /config
            - name: media-root
              mountPath: /media
      volumes:
        - name: media-root
          nfs:
            server: 192.168.86.11
            path: /mnt/nas/media
            readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: sabnzbd-configs
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 30Gi
