---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
resources:
  - namespace.yaml
  - common-configs.yaml
  # wireguard + qbittorrent
  - qbit
  # xarr stack
  - overseerr
  - radarr
  - radarr-4k
  - sonarr
  - sonarr-4k
  - prowlarr
  - bazarr
  # le stack
  - overseerr-le
  - radarr-le
  # monitoring
  - uptime-kuma
  # misc
  - sync
