---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-configs-local
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: uptime-restored-pv
  resources:
    requests:
      storage: 2Gi
