---
- hosts: k8s, proxmox
  pre_tasks:
    - name: Gather facts for all hosts
      setup:
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k8s'] + groups['proxmox'] }}"
      when: hostvars[item]['ansible_default_ipv4'] is not defined

- hosts: k8s
  roles:
    - _bootstrap
    - networking
    - hostname
    - custom_configs
  gather_facts: no

# - name: Run k0s playbook
#   import_playbook: k0s-ansible/site.yml
