---
version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/ansible/**/*"
    schedule:
      interval: "daily"  # weekdays only
      time: "10:00"
      timezone: "America/Chicago"
    rebase-strategy: "auto"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directories:
      - "/fluxcd/clusters/pi/"
      - "/fluxcd/clusters/pi/*"
      - "/fluxcd/clusters/pi/**/*"
    schedule:
      interval: "daily"  # weekdays only
      time: "10:00"
      timezone: "America/Chicago"
    rebase-strategy: "auto"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 0  # no limit
