apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: auth
    namespace: longhorn-system
data:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:F9cl0A5B00SymOo1,iv:pWXatsrsX+HUajD8kbpkZ8tOfDN2GvD9dx0mON1z0pA=,tag:2BmQH+6r5RW07tFcBfBHuQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Ap8RXzF698qPYIrf93betB7s3uQqotzXg0KdE2/zG2r5BqFi7DO4KZGjkIA=,iv:GNP5gpCkP/ukPSoDynlJmJ6qjoYTxMnlzDHHAeUyUsE=,tag:JE/BD4G39Fazo4Wk3bwsVQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreXZLVEZtdkJvcDFLVXRO
            em45Z0U3amZ6bHczR3psbThBYnA0SzdBWkVZCkFBdVlOSzlTa05yY2lGdVZXdHgr
            anlCZkh5VytjbWNJRmEzZnk0bUU0RGMKLS0tIENHQzFoSVV2YlZFUWQyUS9PdWVB
            UThHQmY0dGlQdHNCMDlOd01kRnFtSTAKQnCAbEp3MOC9NEnVGtrAjsGah5C5GHKp
            YphxjMwt40Ikl+Q18G5HYh2CUUBOL5yhvliD9PEePbYtjssGifsWUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T23:14:31Z"
    mac: ENC[AES256_GCM,data:3LH46qmJWxMpcI0QQLOaMaHm34EF6GgDoeOY30seVTh0kRSal/wRsVmX4NxqlrhIoW3cdRTd+VMXfya+fj+HsQqRw/lHmH9QPDowHUIj8nNkGUd6f8ri34mVuhv1nVf4MbR/XgQj2+ypvGbj3qXkOsonlTsFKTDUB3Vnm5hmcps=,iv:zKhkfT04yvNebZ1c0ANP9lWJkLl4RTyoQnT2yyD2BX8=,tag:wR7JGal8cRaNe4cMNocZtQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
