apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:06cTSTQ4Ng==,iv:TPN0uuIydFcKX2+g4ofRC2qx0CZyoKbKxql9zF6AOnQ=,tag:n400Jnv27//6mK1qzXki/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9RqYPCZUY5AY0vmGj/SQnLR9xJXcAa7vujaIdCuxByVk,iv:nQfPAnbGvbWv69Cxxrw3+r24SJddVc8NlDLhy2il4b8=,tag:ri4J9/11XW8mxWrAw+VgMw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:/YKtowQhKKA7WDgSoMP7XbsU5GLRWdkx3QHinPq4Ynl7hH0hwCO2YLSvYuX0TsZfvch5,iv:u+O53p22oBZuI23oqI2BqDWWO6xlTHb5Ae+yZYmyEn4=,tag:0y61WGriakBdDQsRNLYEyQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeXNEYW9rcWU2YWh2MW53
            V0FKYnRhaVBCWU5GR2oxVGxVaEVFcy9MaFZBCllaWGJsRzZ3YktJZXhFWXJoNElJ
            SC9INnZVdUxhWkNrTXNXYkkxald5MVEKLS0tIDc2MWFmaE84cExiaS9ERUFqSzc2
            V3RQVlRNbU9pMkNrRFJSL2s0TmdndncKHYZhMCK2KVfmph69bjLT/oKcHgO4WxOl
            RchAY6W3h9mpRO8G09GJfA8hrs9U9OX36yeCBoh71EXV+gsJFllEIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T02:06:07Z"
    mac: ENC[AES256_GCM,data:ZTc+/IBuSg6OJC499aPO59a5QBkwUG8GbEsv8UKVfGnIbMMhxHP+KD1tE0IlKnAD9N2Nr2Lb8gR4eCjFL28pFQWiwONH62Y14nAv1x9bidjVetiEZOPSwpApWbPRT/gFJZ2w1YZPdoISkFCUkjUMz69RwDUg86FafoOy3Okl2f8=,iv:tjDKiJZYKTBsS6rGV/YrYv23JOxIYkr1A4QXhKNqLfQ=,tag:/T2yCPUe6BmpbQAh1dchBg==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ/+LCg8zRZr9X0ivFa68nKJh8OPE//vhHHGZ52+bWiP+6oA
            VoM2YHy9IO0xgtXY91We9Ayn45TuuHlKH6i2YHGMWmpQDcq/YPseNkyU00BJBH/h
            LK3iGyzU5K593YEXA/hJlp/Kn5dQnCGYBE6Mp9lkwoshzUedmBstGEV2lSn60kbv
            lXmjDIZmm05eC5rhJKZm/pK05lxXqtETfxHzu786x6p2UXut1y7p8Xq573yYbAYO
            BxkqCPI49gvHiuNsf/SZfyizNN0Hwge8FydX7SxnBMtbW/yTJB1tgVObg6zlwOl7
            1tctegzTcgkdln96vwCQTLaRakSwvRw5DRHF95zylcmJ/oJVV65867tHb2ZrcXYP
            i054EQ6XaF1A/UCNu/5ET/YBPtpDEXVisx8366AHO7b0BdtCghc9RUIyh7rTBZri
            zWdh7hYcFS5wbhR9knCfxL5ZzcPeM0GSI3I6ud4c2NKuGsm9A87qtmDD2rjnSupJ
            baGKFHrbXfgmqVhgXpTjj3pHhW8QVJ8UWMYFnFrbyFV231Uay9VzKX/1msxSnMdC
            jd4Hu9WW7YbD+iFK/z0M1pOaNXwNt+UEXvLkScTVD28XgculOu5WEo26XqwrSSej
            K0T2bg9Z/G8knJivl1s1PGOfR5BgJjKyqOj0enEBGcqsOxjagThB8UsxBefAppHU
            aAEJAhCQTKu7nCpH6bA9GSs9k5oFcHH2qMCva/mVm+/5a9JsfcDEcyArC6Q38Rxb
            QgnNdXxkFFrpD8qqmNXd3CPMlqC3t7oqJBSdKRuuFEKw0x7g647m5z3uizhZqYBk
            UL6AkuzV2pyF
            =wjPp
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
