apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: auth
    namespace: longhorn-system
data:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:F9cl0A5B00SymOo1,iv:pWXatsrsX+HUajD8kbpkZ8tOfDN2GvD9dx0mON1z0pA=,tag:2BmQH+6r5RW07tFcBfBHuQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Ap8RXzF698qPYIrf93betB7s3uQqotzXg0KdE2/zG2r5BqFi7DO4KZGjkIA=,iv:GNP5gpCkP/ukPSoDynlJmJ6qjoYTxMnlzDHHAeUyUsE=,tag:JE/BD4G39Fazo4Wk3bwsVQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaDg1c1EvSng0eGFGdEQ0
            UlJONnkyZDRCUlkyU3pMREVKeXlLQWppSTJ3CklYSUdlbnBVVFpBZGtrRGJoSEw0
            RVpEU0ZoYnZIaExKaUNzT2VUUzlOOG8KLS0tIDZwcEFiNExlRnpDWlBGRGo3a1Uv
            U1h0ZTlzcy9DTTlWMzhhTlhma2d5QlEKZy0O75KrlGDNlRbDQviAvc1/xYxFzZXb
            XQenFRLndBP9sS+GXDUfy2EMN9dbBdjE/zY4ThwfpVCaUuFbaK2oKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T23:14:31Z"
    mac: ENC[AES256_GCM,data:3LH46qmJWxMpcI0QQLOaMaHm34EF6GgDoeOY30seVTh0kRSal/wRsVmX4NxqlrhIoW3cdRTd+VMXfya+fj+HsQqRw/lHmH9QPDowHUIj8nNkGUd6f8ri34mVuhv1nVf4MbR/XgQj2+ypvGbj3qXkOsonlTsFKTDUB3Vnm5hmcps=,iv:zKhkfT04yvNebZ1c0ANP9lWJkLl4RTyoQnT2yyD2BX8=,tag:wR7JGal8cRaNe4cMNocZtQ==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ//dOgADOKFU+PwomyggwAYOC6jqwxrqcBFp2OY2dnSdNch
            RRlqsmi3XIuHlT87umDvne04vWcKA836ATp7ohqRqdWccCA+mA8mrnWsmz3XiHqe
            utdqZxg7T+qhYbwB+ZTgE3HCunrZSR6Qhb1I9H7iAywm2gl6geBE/CgmUGK9o/rb
            IMD4unNhd3YFpcUr60CQlKlcKLtgqpTntMncFoTLoiRmzoS+HOfkK2mWZHSJDLI0
            G5lI+RMzJyb/spIYQyeP/yMOw15GJU6g2SEIS4+HShb04uUTJfqHlmOJBk314Pf0
            gySAgNYRxCRomF0RLh/j+kwvFpkNzLblcBPqfJtcss5vw78YnMiVLhj8EhGf3JfG
            d/LxgLiA0wG/uBAmkFRdy0AVvMfPi8sH3KZTdao8kmeGRZxfN5B0NLHfIArefqbx
            c9tAaodiTTKjgbBofsXWtZHRILs/EDAR2NSCw2gUyaH2ROeKmLy7M9BJ2yxF04VR
            r9Aah32/1gNBDzwPto5SZZQ9QIDmA8P0btxgW1LdrIgUFW7pRP7ZAAk62urn+nfA
            ptU8hvZRZ9BEF2YK/mAX5rdwKs9hzzh3GFKLRupq/j8ZKATS1LOCR15mTJmJS/q4
            bzoQCqP/bB1q6CawQOB/uSh9aTN4+23Wos8c/2b8fQiR1WgFp06k9t+LfS96GS7U
            aAEJAhCxcYb7B5IyhHmnkdUgoYFqz/Shf9VVVDzK8GsgNOIe4KYFZm5KP8CI23WK
            ii4Tts/RWjTu6MG8va5x27ncHZR5yGH+ebtK+D80Od/nTOZqrQ67a8I40mV8VV3m
            PX7o5bQCSaxP
            =8fJM
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
