apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:06cTSTQ4Ng==,iv:TPN0uuIydFcKX2+g4ofRC2qx0CZyoKbKxql9zF6AOnQ=,tag:n400Jnv27//6mK1qzXki/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9RqYPCZUY5AY0vmGj/SQnLR9xJXcAa7vujaIdCuxByVk,iv:nQfPAnbGvbWv69Cxxrw3+r24SJddVc8NlDLhy2il4b8=,tag:ri4J9/11XW8mxWrAw+VgMw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:/YKtowQhKKA7WDgSoMP7XbsU5GLRWdkx3QHinPq4Ynl7hH0hwCO2YLSvYuX0TsZfvch5,iv:u+O53p22oBZuI23oqI2BqDWWO6xlTHb5Ae+yZYmyEn4=,tag:0y61WGriakBdDQsRNLYEyQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT3dwQ2d4eldIb01wUDdO
            K0xiVzdqMmNSUVlOMGZHY2dFRHpBWG4wNFhJClFzc3lKbVE5dGRXSlA3QXIyRjMr
            SXU3UDJrQy9xZUh6S0ZNZ1pidGlGbncKLS0tIFBWcTJiWm8rYzRtV1ljY3NIa3pi
            ZUpUb09hMlBSOFRiK1Rtcm53RVBEVFUKJ2+SvTfeRIxTs3eBRDupHGlsaMhVcH33
            9VHdruSm7H+ouSmeyU5She1HXuCNVo4juXgeCGY72PRXdz6MBMLpNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T02:06:07Z"
    mac: ENC[AES256_GCM,data:ZTc+/IBuSg6OJC499aPO59a5QBkwUG8GbEsv8UKVfGnIbMMhxHP+KD1tE0IlKnAD9N2Nr2Lb8gR4eCjFL28pFQWiwONH62Y14nAv1x9bidjVetiEZOPSwpApWbPRT/gFJZ2w1YZPdoISkFCUkjUMz69RwDUg86FafoOy3Okl2f8=,iv:tjDKiJZYKTBsS6rGV/YrYv23JOxIYkr1A4QXhKNqLfQ=,tag:/T2yCPUe6BmpbQAh1dchBg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
