---
# ip_base: "192.168.1"
# routers:
#   - "{{ ip_base }}.254"

# ip_base: "10.0.0"
# routers:
#   - "{{ ip_base }}.1"

  # Mapping of what hardware MAC addresses should be configured with specific IPs.
mac_address_mapping:
  "dc:a6:32:09:40:f9":
    name: k0
    ip: "{{ip_base}}.100"
  "dc:a6:32:09:52:c9":
    name: k1
    ip: "{{ip_base}}.101"
  "dc:a6:32:09:53:de":
    name: k2
    ip: "{{ip_base}}.102"
  "b8:27:eb:c0:7f:be":
    name: k3
    ip: "{{ip_base}}.103"

# Nameservers to use in resolv.conf.
dns_nameservers:
  - "8.8.8.8"
  - "8.8.4.4"
