apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
resources:
  - cloudflare-api-token-secret.sops.yaml
  - lets-encrypt-staging-issuer.sops.yaml
  - lets-encrypt-production-issuer.yaml
