apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hnvNX9/BNwXD,iv:XmNwfS+iiWFBdQiA8qpEwXO+Y/75a0gDuYP3m9hFeU8=,tag:bx1Y6pYG8ov1HSPpCOwIdw==,type:str]
    password: ENC[AES256_GCM,data:GTep0g7155vVgAX2309i2b3tV9qAKRafim5WszRotiY=,iv:NZoqD97iw4wZOAnEj+utdkpsBeNt+Yqx9hTpth3uxRM=,tag:4c3yczT0Unush0rXaClXGg==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGV0ZjVQWEFDejdOcHdq
            ZFIxbjNOSzZsbUNxMVh4RDdHN1J0NlVkSlJnClFqN3U1dEhQNG9XMGVFQ3gzcTd5
            TyttMjY1RUxhNVhpNldrM1lmeEh2U2sKLS0tIFBsU3hNY0tRUUpMYlYwYjNldGcr
            NTNPa3BuQXEvekF1YlZlTkIwNCs2Yk0KiqlryJcK9NJgKruj0lgyB7CPy/cCEAgA
            UzLx2A5Q1WxnHWqRaXjXgz41zo0nZo26ov6piDzVPovBUPscwA1stQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T16:59:45Z"
    mac: ENC[AES256_GCM,data:gwHrbh8wQeJJJyVsWctFzqOuwqb7Mx5usLWnrJTYzEvVJtm2oFMQ1WkyJ1ziVkFbkyUiGCZihW+pNRIpA4VdHgZS3OOtNIOyqG3kBT7tvf3DmpGc0qh6rQnvduLyCkfX5n2C48+QrXW2NhrFpCVjY8u9DmtbJ/MSqVpiuHovtgY=,iv:nUORBAq7tSQbCdt6Q13Yj8IkjmCRTg+NH7s8KNdR4WE=,tag:hOUz5ZR4tkGuAXMqmrYP9g==,type:str]
    pgp:
        - created_at: "2026-05-19T16:59:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/ARAApKGZ7Zi4gZTY6NhktyvH8Z7qbiYRlOMfhLCOxM5Frh2H
            Ly+4occBcfRflIhb4+kNTZq8A4AePK8O7SeJRfKGLc4ZuX4s1OSfb4inadPkWfd8
            8xf1aqnXLIrPr06tYAlOMwbg7cxviO8D9RV6xgkv5Ciq6+KlnRqwWQYozphRqI3f
            bqhAaDjgG+4jZU1vS9Vdea5fWgWy2UGFpwWm7+JMKjYKjZr5EaFxUalEF5WOizvF
            0953TTv05v7oV5BvtGoZTomBjzYy39tdrVxlN5neZT0iDPGEw3IVapjQw8vOAN1e
            F2kWcz4s5Nv8y4KH9FzfvnZG/T/fosoVEvHfY1sAodruUF5FcamXuE7IWgyij20h
            F8oLZwEWSwEDbHO2vRznmQ94rBIx/gcvIqwT/jwX5Oo4EUAMyycyrmJyN4dCn+8b
            iccjrspoIBoRn5kzWIrcjbZ2IowyTiXCuH20ftwMsTMhB0Zosf17cVORy/CumFoa
            Alv5hJvzj4215qG6ugPyKu9GQtjX2VV3Qv7dDoaU8DK+b/KWuqMb34iVNVrlOqNG
            dQ5JMmep3IC/0jGBYKI6Yxtu8R5juFX6pIr/xYRa1P7AMG90Kzgwv1kg+YB0Kjkn
            pZKXnm1kQ0jLBhqsFlyDt9w0C+yI16ItCgmdO8awmSVsaOluy2lR4JWWroIjwCrU
            aAEJAhB9yuwJ9ftbrecEJ0bLAKgRIO4GRnufqDvWysMG/eTEXlCmuJtWLwmIPxEO
            Gz6BxCuXJkgg7IovH8URQdX8hn4pxpFlviyUeLNMGZ80EMU+WURbGcvfw8eJKkvU
            zTubyhqsN7NV
            =0m1L
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:kqWfEnXNs8hEKGGnZP8iQaRDEGIHgvE3oHVvXCWePgpN5RS8a/QUsDh9wPOHn8iWJXLUs/vS+ev2pROYjEbKAg==,iv:4SvSPqULb3Z/RmlVUFliTeuYUcYfsnWvJykcrj802is=,tag:oiZqnTAc5FWZcudYAf8DQA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:ZvR64o/I5AQpPR5AOma+iY/nV6Xi1zbEI9CxM+VZ8uk=,iv:f6vo38/5f2WCfg3u5fp0f8PVQSGEJvs1Y64/vMOY4Jk=,tag:g+3srgX94GhZ9ExRmDrC5Q==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGV0ZjVQWEFDejdOcHdq
            ZFIxbjNOSzZsbUNxMVh4RDdHN1J0NlVkSlJnClFqN3U1dEhQNG9XMGVFQ3gzcTd5
            TyttMjY1RUxhNVhpNldrM1lmeEh2U2sKLS0tIFBsU3hNY0tRUUpMYlYwYjNldGcr
            NTNPa3BuQXEvekF1YlZlTkIwNCs2Yk0KiqlryJcK9NJgKruj0lgyB7CPy/cCEAgA
            UzLx2A5Q1WxnHWqRaXjXgz41zo0nZo26ov6piDzVPovBUPscwA1stQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T16:59:45Z"
    mac: ENC[AES256_GCM,data:gwHrbh8wQeJJJyVsWctFzqOuwqb7Mx5usLWnrJTYzEvVJtm2oFMQ1WkyJ1ziVkFbkyUiGCZihW+pNRIpA4VdHgZS3OOtNIOyqG3kBT7tvf3DmpGc0qh6rQnvduLyCkfX5n2C48+QrXW2NhrFpCVjY8u9DmtbJ/MSqVpiuHovtgY=,iv:nUORBAq7tSQbCdt6Q13Yj8IkjmCRTg+NH7s8KNdR4WE=,tag:hOUz5ZR4tkGuAXMqmrYP9g==,type:str]
    pgp:
        - created_at: "2026-05-19T16:59:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/ARAApKGZ7Zi4gZTY6NhktyvH8Z7qbiYRlOMfhLCOxM5Frh2H
            Ly+4occBcfRflIhb4+kNTZq8A4AePK8O7SeJRfKGLc4ZuX4s1OSfb4inadPkWfd8
            8xf1aqnXLIrPr06tYAlOMwbg7cxviO8D9RV6xgkv5Ciq6+KlnRqwWQYozphRqI3f
            bqhAaDjgG+4jZU1vS9Vdea5fWgWy2UGFpwWm7+JMKjYKjZr5EaFxUalEF5WOizvF
            0953TTv05v7oV5BvtGoZTomBjzYy39tdrVxlN5neZT0iDPGEw3IVapjQw8vOAN1e
            F2kWcz4s5Nv8y4KH9FzfvnZG/T/fosoVEvHfY1sAodruUF5FcamXuE7IWgyij20h
            F8oLZwEWSwEDbHO2vRznmQ94rBIx/gcvIqwT/jwX5Oo4EUAMyycyrmJyN4dCn+8b
            iccjrspoIBoRn5kzWIrcjbZ2IowyTiXCuH20ftwMsTMhB0Zosf17cVORy/CumFoa
            Alv5hJvzj4215qG6ugPyKu9GQtjX2VV3Qv7dDoaU8DK+b/KWuqMb34iVNVrlOqNG
            dQ5JMmep3IC/0jGBYKI6Yxtu8R5juFX6pIr/xYRa1P7AMG90Kzgwv1kg+YB0Kjkn
            pZKXnm1kQ0jLBhqsFlyDt9w0C+yI16ItCgmdO8awmSVsaOluy2lR4JWWroIjwCrU
            aAEJAhB9yuwJ9ftbrecEJ0bLAKgRIO4GRnufqDvWysMG/eTEXlCmuJtWLwmIPxEO
            Gz6BxCuXJkgg7IovH8URQdX8hn4pxpFlviyUeLNMGZ80EMU+WURbGcvfw8eJKkvU
            zTubyhqsN7NV
            =0m1L
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
