ansible_user: michael
ansible_become_pass: ENC[AES256_GCM,data:n+LcZ/57UX1gdulAHgAvbK3PWD/BqdRngQ==,iv:eeNl91i8nldANkrs32Vq0cdXqKKwgFDBefFTC/ZoMsU=,tag:fkJRkg810aWZm5uHxOTcOg==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S0g4TDhlUmNGS1VjNDlR
            NGJNU2JNL25wRklsdXB6eG5jRElqNVJ5YWtBCmFXeXVycU8zTHdQL1cwRVpzOGVH
            R2xwRUxzNlhTZ0ZqYzhvS3hkUDZ1TjQKLS0tIHVHRlQvbnZ2UVd2Si9yVW1jaGpN
            Zm9CQ3N4QnhqYStUWVkwdTFLWEpqODgK9tFwk8B0iYHVAmYWkCw/whVS6yKXnRxH
            lWkTAA5napE3ULBFQjyf54KIzsL7ph3JeiXuoYmxmrCxnGB9ndeVMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-20T21:55:22Z"
    mac: ENC[AES256_GCM,data:GqXDAgUemLF6CT1L/GznoZE4UAYeQxKIfWYRyHiHR+2282nTM/VLeku4JgZv3MwIDoZJ2gv5/ZqPManXanze4YhLE3SQyWIjLwDyGDh8UzP91I5u8m7173Qn4rlpHIgdo+Ih7D2HnA7MDgbfCBsRxMQH8I6RkdskFRLItN6rX/4=,iv:m9EnkiE1kNCU2fzd/Oc8kvgWkU7rQuqzNbbYacnv02s=,tag:2ru62aeJrjQKkPNZps0zAw==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ//VxDbATddKyIpnP32ZOibgKb2oUFUO2RR7PfLtsWcS9MR
            BtiCD4O6L17NPnDsZAPMqj7lQ36ZILWvulvOURqhyR48efSy9SqSX1NRi9WmsKQi
            NfwIA6iqmcYdTZmHNEO31T+zE8JdrswclKrLdGo1A3GHRwL5lDryKgfpucbZ8IBn
            qPSR49Z/9UtcXlG/1ZkNxmaev/pFn0Z7d+jHgwdMIK3zT250qIQLFERPpYxqBVcp
            YTk6hIsygzKih3aPC4iA5gd8F4q3MAiB7okFgRBgz9Zor1vcitgg+27e/pRE9a0b
            eUMhv+n1/VN76a7z2HqvN0hzANy1tlJeQ+QvZJ0dalZiyK4vVY3/EigsNWopaxwY
            6uxBpHDU20Lb4NRCxwVoASaH9yZgEMY4IE4bTGH3AcPhKnZMDS7pEBJcHQAIgWN8
            viJm36hXRXDR+ZQt4N6jaTaspv8EZne0+BqzjY1+Lz4OMEd6B8rvdhFzXSLzMj6x
            2rDkFfMv4s/19+VQVI3hz8AIxQ0rOotPabcGAWRgw9O1y/TUb4niPMDCsf4nJD+m
            F/fqmdWXP0uMwTz4ZqpcqIX9D/9T5FcJbitVDIY6Lg1i9bJfsuaDIg4rHTwCeTCg
            WyUXpRO5Qj6INGVCto+TWc53gz2rGTRIYJ4RT8Quj6+lA9LCeGFUzhZMQWw0kJXU
            ZgEJAhBqKELvADMr4fqYSwMuAF2Tk9Lq/CiPV8gQxdaXmhSWLwYUxb8pCkXlYjq6
            /UGAbsiM62NN1VnIDO6TXcUPar1hk3PTFsBUeB5OB8KLOy8tdXudGhZp3XyFi3jY
            27GEug6CyQ==
            =4b2h
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(ansible_become_pass)$
    version: 3.8.0
