ansible_user: ENC[AES256_GCM,data:8ZzrnDpILg==,iv:JF8dkv9MNbze5+TEfgKxGtKl2r/ky3S4sRIoAfEaKxU=,tag:MiSODShrQlNHNGFxoxhm5Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8UROgadvWuCXAf8IiWltQgzZRx0lqx3XDA==,iv:tjoOLov9yt0cFEEmTo1NUsCbBjbA1siIho1RYnN69jw=,tag:eOoFMJ66aqZCBHcfCHY2Sg==,type:str]
sops:
    lastmodified: "2026-05-10T20:38:42Z"
    mac: ENC[AES256_GCM,data:b2VIhCN3rAorZDfEeHTDMBaZrBKIrz7n5+Iba3RHj+CBc+l2EE8U3SgDehJOUzYMr7woCrOOsM+myl+wpwUPQnYkvbztBN3p6xMVn6W9AeztKhaFkZSqSjKjWqAwd8GyRiyn39HCmJFKJW0Cx9h0Ud6xH5gHiJ/VDTg6DmGiJLc=,iv:T4sdPGfbT4Ps55xgo5pBJFGjDwFnefupcz8UH7iuSfg=,tag:oJxSwzHj8xFMkF4EFmPHbQ==,type:str]
    pgp:
        - created_at: "2026-05-10T20:38:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDAQ/9GLFuA2UiPUmyI4Oj8R7/PTG0YtBI9+7xu6aZwbeusc8b
            cdazeDsL5PWouQfQVK++R0Z1g5bkid7P6yg+pUfyixHJf/kk3QgbXOs7zqPeI3CI
            vU0ATUk0/SYPi8bReCq2L9M25aen3x2tpmDuHIgf6RMFwMYR477XiHvb5I1aHWkO
            CaVt9ScP2kEFkqsXJWbMoESRgRSUy2TfsmtGe1bMBfpVbCA2pg5658YXW8bwt4ni
            4rhulQd1f8t6NmgH1HstbM11eXUa/Cq/cjNkSPiKNW60B2mbsFLl1fIHiVYer6Hj
            Aktl8feguyVI16WAeudUSYBeHC5uauDMvP1n3AaGjANnfB/HSmn5lzjiBE4okqrX
            fA0c3lD774GRDlcZzGV61GaU+EU65g1iDHswte7NDVdpnKX9UVAU7PiRAqYJHR2x
            c8oz/JbVSTuLWn3dNBxb+QcCzCtZdAd5dY8AGygIgnMijPzQ1gsXGCKu8ICvFnCj
            qiYASfpL97jOdr0lV+sUukjpL0nT0yn2UJDDzA3VCtnjyzfIsg1KOhpluqe5kU7t
            w10lfMheqHnO95/62BqnmzXl4+khBMVt9EYfm2q42qdBochTc3Ft6K4rGl8aaxeC
            ZeSYMhr36Kr2OEGisFS0FWzyA2U4+BT45lzES0s2xMvXcgfuoBIYk8wssTexLCTU
            aAEJAhA4JAxPQrwwfpuADrDvVVVN6NjlR3Fv+V+a8xPIYaCq289reWLh6BXaC6b9
            RVr5Ivn9binTM9+AcYNMXarQcYFQeg8JU/wf+e0Z9ui0MQbpt0B5Ldj8nF/hhhI+
            q+lvBbT9JYrk
            =8Nti
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(ansible_become_pass|ansible_user)$
    version: 3.12.2
