apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
resources:
  - wireguard-configs.yaml
  - pia-secret.sops.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
