---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
resources:
  - wireguard-configs.yaml
  - pia-secret.sops.yaml
  - deployment.yaml  # scaled to 0
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

components:
  - ../0-components/health-checks
  # Note: security-context component disabled for qbit due to:
  # - Init container needs to run package management (apk add git)
  # - Requires privileged networking capabilities (NET_ADMIN, SYS_MODULE)
  # - ../0-components/security-context

patches:
  - target:
      kind: Deployment
      name: qbit
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: qbit
      spec:
        replicas: 0
        template:
          spec:
            containers:
              - name: qbit
                startupProbe:
                  httpGet:
                    port: 8080
                livenessProbe:
                  httpGet:
                    port: 8080
                readinessProbe:
                  httpGet:
                    port: 8080
  - target:
      kind: StatefulSet
      name: qbit
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: qbit
      spec:
        template:
          spec:
            containers:
              - name: qbit
                startupProbe:
                  httpGet:
                    port: 8080
                livenessProbe:
                  httpGet:
                    port: 8080
                readinessProbe:
                  httpGet:
                    port: 8080
