---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
resources:
  - wireguard-configs.yaml
  - pia-secret.sops.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

# Note: security-context component disabled for qbit due to:
# - Init container needs to run package management (apk add git)
# - Requires privileged networking capabilities (NET_ADMIN, SYS_MODULE)
components:
  - ../0-components/health-checks
  # - ../0-components/security-context

patches:
  # Fix health check ports for wireguard container (containers[0])
  # Use JSON patch to replace readinessProbe with exec probe for VPN check
  - target:
      kind: StatefulSet
      name: qbit
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                IP=$(curl -s --max-time 5 https://icanhazip.com/)
                echo "current IP: ${IP}"
                [ "${IP}" != "$HOME_IP" ]
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3

  # Add health checks to qbit container (containers[1])
  # The health-checks component only handles containers[0], so we add containers[1] manually
  - target:
      kind: StatefulSet
      name: qbit
    patch: |-
      - op: add
        path: /spec/template/spec/containers/1/startupProbe
        value:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 18
      - op: add
        path: /spec/template/spec/containers/1/livenessProbe
        value:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      - op: add
        path: /spec/template/spec/containers/1/readinessProbe
        value:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
