apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pia-auth
    namespace: home
stringData:
    PIA_USER: ENC[AES256_GCM,data:xHgYxbnHBlw=,iv:2Q70T8mOKqGeYIPEPRH9f/iwdxZ9i6O+beQJuGhNUEs=,tag:hQpmJ/HjD5t5qAbyHqEJyw==,type:str]
    PIA_PASS: ENC[AES256_GCM,data:kKiFbnNROSItwQ==,iv:VRs7d5Xgr0te24xAG5BIx6Wtlbta+y9Ju3faHK0TP1I=,tag:tsqs9US2sATredDsc+thYg==,type:str]
    HOME_IP: ENC[AES256_GCM,data:4qFhQ/DCdJw7Ux/Y,iv:j0baBDE3wal2tR/z1psY7FkbYVJOlIa+n1TP+kC5lX0=,tag:XYL5MscvMKcaVyptoz6L+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-08T21:34:40Z"
    mac: ENC[AES256_GCM,data:KjpgFejSNLxCWhskOV2oeDP09eof2AEhuPXEQxtuTBcyc2AdjxbH3ChRMmjj4HziUthdmrEvr0zoPiFlPWCU7GYGoV0HU0wzuruwwIdT4mQksbFJcvspz2046muSL5tIqGyS4KXvpJTHxIwSO66pHATpdC/uqf206dlsbp3hBPs=,iv:2Tv+ew/I5cmPo0wuwYnQiGLi1TKL2/AdjMv/60jzc1Y=,tag:y3CAzbP+BzBw6IywAE36yw==,type:str]
    pgp:
        - created_at: "2025-06-08T21:34:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDAQ//TiBIm6+YQYjjYrkTWp2EWfA1zpGtOKsVVTIPNmoxUBC2
            zCErgKd05Du2l3NT1J5g4TQGeBGsuAklFK580FY5Gi8KBPqdO54ScTCR5UvYnCfR
            LYBkxjnTY4gijHSTN5YP6cQn0HnYSP4nsPmEqhLCpNLOxpAkKei2SDHj4Jgf5+Q6
            l2pWNlpyY13wFSPVqiXImrADdLr1HGg2gf+vbgZEEu1R3WFRhfjCqNCgah4lEiGE
            Hp2Ep5o5xaf9DYVVkQkLjp6NF7EaSAU4mOHqeeSPdVqf60PCIb5+9SjOlE/KOAt3
            5FV2QFIg2OzKYUdtympXIQE65GVD5AMF/sjqT1ipthzNFCS1NqNtw6x7miBkSoi0
            34UNQaTYzUHTDNKiriKtqUrWfDYgYFs2V3v6LsKwfFSKkmN2ZaRj2RcPMoilDu5S
            hCnyUNmxyXiiUMWeMNnncAZGzbvbyfZZ5Xs70ilq/GNihag/vSXa9KQxE2ASLcIe
            8SprD33GK9pIJTpwOz35ry5aJJ6XqFmJkG6YRc/mO0YtMlFnyPJhfxlipTfeVpmv
            uZLjBvdMKEvx5ME/fopVdx/DnH/O6EdWR8ZRXPMC+ww0EZZ9aKz8gbPRi6DqRav3
            Nu5QGXp0aKNb4SbFrY/iKZPEOllhbXiJ/pmfiEbOck9y1IU9TU6sZr7WiPbTSbTU
            aAEJAhBzkOue8V1upwziGFum190JgOh7t3qUEZst6IvqI8ndZiI+2ePc+SuVVijq
            I06NQ/ffWwabBNG7yY/HNr2oRiIHDDS5XXqRMaUl31p93v0jHFGwY0l5GPe/a6lc
            y5lB+/+rfV2z
            =ukVv
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
