apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: protonvpn-auth
    namespace: home
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:TVYQDXIM9/cQBE4gNglb3C740EdvQLdbPMuWZOOTuwOgC6ySWbiZtyj8pYA=,iv:3xXJjtM+yOqBVBU0BGH6zuX2Ag/PLzU45RGd9SGU0QA=,tag:fNaAes7RAbV695FwF159Kg==,type:str]
    QBT_USERNAME: ENC[AES256_GCM,data:uIOxbAA=,iv:3eN4urOPbpgCUXJW3ee+mkalXBzs7EVNQ66eC8/bju4=,tag:NLs2isRTVMdHgHrksApHag==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:H698CB7g3t2KLq//1AdtXEdGh/AqX8/d2kd5TpdGAWU=,iv:a5CXaKHDUi5YoLiWsZJCjduRGWTf/Ojh5orm08dURDk=,tag:ldKXij8ewuLGtZtNxBx/KA==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWU1BrWGpQa095RkdHc0sy
            SDBZVEVMVFBtWjZzNVkxK1lKcDJnUzhhU0Q4CmpVeEFjU3dtM05FME5SMk5YdWQr
            ci9oRE9kbXRueWRpWlgvVGdQM2JsOHMKLS0tIEFjOVVST3RaWS8vN2NvYlY1Q1Ir
            N2kwTVBuVWk2TDB2WmFuS2Z1c3RBV28K6WZ+lPHrJKlWEtSpVxse/T9SCvMb5HUc
            PpFkYr4WFXtbZJa1mlJ+89WmbWyA1bD8SZH5n2h8lBYau92BkmZyUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:48:59Z"
    mac: ENC[AES256_GCM,data:cOeY+enE3AxtRotSOEE3UK0uP91SiBDomgsYrc9kUrKaNn4iP3tT7AQzfHh8JB3UFIGfGYyazazszFjuW7ZUREVpS8RKxFGKLCULUsdrHYaLa20xOogsxqAUkOb/wVewVjLxqv5X7pCf5YKrTk+hE7mBJPZcAq6zVx8OXuUvb6U=,iv:TRlR0X6XIWH4Z5z09fa3R/Kit9YeosVzDuMIIypKEFs=,tag:0ve0Q+nt//clXaF/kEQu0Q==,type:str]
    pgp:
        - created_at: "2026-03-24T22:34:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDAQ//ZRkaXnlDO4HGEeAv3u1OwgfJ6KAmyN1W8VBYQ0Z5QM5n
            7WXSB6eAquAnHgKXBs2KxAjrrwkA6lkbJBjgLzkDkKecWFoZOkyK4BxzIX5FfkZr
            RDmkjr4ZQs99rZ/jJgWL46+OKMFlm6QHUORKctT7+utVphtuzOSemFbMEEHqsD3d
            5ZMTePgH2yQC+ZYYRRJmnqdgk/xnNMA5QnP3QpkujL2+/NYivPKspwWmxeZB0uHK
            sbBc2T/0x+vQWwIJNO0UcSINY4mIOgpY+JfyOPMiKcVGRj5BjASfoAgMhF9KLbNh
            w9KdJn7/4XJVss6so1e5LbCWlHjNF5j0ytoSBv0Twi93o0h2d7QWF9sdQCULJvDi
            9IP6zajvDquPpLmem/KoEmF1pjM9RQBi+MiWX6YqIFuOsbLvOXw5WcukZOpuPhiI
            STQIA1liEz5IdOeflXYUc3sgs2WMxDgLeZkF+PNeiiWmbyfyqXhaHKN6YU0I4k+E
            pFozul4TuArUwADQqeuTOnKUEgROXjOG5g2geaS8dCudGLxnls75rlQmflQ/8wVl
            IrSHQZSCXy/eJidAlKSugrKC9mnD/Q5ank4Wq1hlV4l/JaImnrl6d7GSBg1r+Cck
            adiH6ds50vPqukpVvdU8RiQPvAuORZ7+4f2oXGI3i9w2pC0VNqh8Vw9GWsoMBqbU
            aAEJAhCRN46FJd9sQgeAUlcmJz8sK6mPrneICx5FOxqCUkFBYLclB8bZIYlOPuT4
            SOWgRtgI0GIkaAHmQ8y/AluyrWAvhyPq0FBT+y2lXslZj0rcDTp5zvthL6KEIgl2
            lDAQEu8H0BG+
            =t27n
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
