apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: protonvpn-auth
    namespace: home
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:TVYQDXIM9/cQBE4gNglb3C740EdvQLdbPMuWZOOTuwOgC6ySWbiZtyj8pYA=,iv:3xXJjtM+yOqBVBU0BGH6zuX2Ag/PLzU45RGd9SGU0QA=,tag:fNaAes7RAbV695FwF159Kg==,type:str]
    QBT_USERNAME: ENC[AES256_GCM,data:uIOxbAA=,iv:3eN4urOPbpgCUXJW3ee+mkalXBzs7EVNQ66eC8/bju4=,tag:NLs2isRTVMdHgHrksApHag==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:H698CB7g3t2KLq//1AdtXEdGh/AqX8/d2kd5TpdGAWU=,iv:a5CXaKHDUi5YoLiWsZJCjduRGWTf/Ojh5orm08dURDk=,tag:ldKXij8ewuLGtZtNxBx/KA==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL05BYnRpWU43OEhiaDFm
            VDdBczFIZWxvS00yVmV4Wm9sMjJwOVUxMDJ3CkxGUzBoU2p6aDlvMEZ4VXR6d2VV
            TWlHN3BYWTJUcGxPQWVtdDVBQ2tZMXMKLS0tIDYwTVk2cytwayt6L3ExV3FTL0dJ
            ZkplREdlbzhKeXM5YTFyeTFUMFlwNVEKpeM4JIfp9BJxPOlTykY0Wpa6S7H70BFO
            G/B5RUIzx1YJ6TQkxYrG8cQMctmAbTexegPys/8DpPe3unMkrakGQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:48:59Z"
    mac: ENC[AES256_GCM,data:cOeY+enE3AxtRotSOEE3UK0uP91SiBDomgsYrc9kUrKaNn4iP3tT7AQzfHh8JB3UFIGfGYyazazszFjuW7ZUREVpS8RKxFGKLCULUsdrHYaLa20xOogsxqAUkOb/wVewVjLxqv5X7pCf5YKrTk+hE7mBJPZcAq6zVx8OXuUvb6U=,iv:TRlR0X6XIWH4Z5z09fa3R/Kit9YeosVzDuMIIypKEFs=,tag:0ve0Q+nt//clXaF/kEQu0Q==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
