---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-downloads
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
