---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbit
  namespace: home
  labels:
    app: qbit
spec:
  serviceName: qbit
  replicas: 1
  selector:
    matchLabels:
      app: qbit
  template:
    metadata:
      name: qbit
      namespace: home
      labels:
        app: qbit
    spec:
      nodeName: k3
      terminationGracePeriodSeconds: 10
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"

      initContainers:
        - name: wg-init
          image: lscr.io/linuxserver/wireguard:arm64v8-v1.0.20210914-ls80
          command:
            - /bin/sh
            - -c
            - |
              apk add git
              git clone https://github.com/pia-foss/manual-connections.git
              cd manual-connections
              bash ./run_setup.sh
          envFrom:
            - secretRef:
                name: pia-auth
            - configMapRef:
                name: wireguard-configs

          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
            - name: wireguard-configs
              mountPath: /config

      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:arm64v8-v1.0.20210914-ls80
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"

          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          ports:
            - containerPort: 8080
              name: qbit-webui-port
            - containerPort: 6881
              protocol: TCP
              name: torrent-tcp
            - containerPort: 6881
              protocol: UDP
              name: torrent-udp

          envFrom:
            - configMapRef:
                name: common-configs

          env:
            - name: HOME_IP
              valueFrom:
                secretKeyRef:
                  name: pia-auth
                  key: HOME_IP

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  IP=`curl -s https://icanhazip.com/`
                  echo "current IP:${IP}"
                  [ "${IP}" != "$HOME_IP" ]
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5

          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
            - name: wireguard-configs
              mountPath: /config

        - name: qbit
          image: lscr.io/linuxserver/qbittorrent:5.1.2
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"

          envFrom:
            - configMapRef:
                name: common-configs

          volumeMounts:
            - name: media-root
              mountPath: /media
            - name: qbit-configs
              mountPath: /config

      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: media-root
          nfs:
            server: 192.168.86.10
            path: /nfs/media
            readOnly: false
        - name: wireguard-configs
          persistentVolumeClaim:
            claimName: wireguard-configs-local
  volumeClaimTemplates:
    - metadata:
        name: qbit-configs
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 200Mi
