---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: home
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      name: radarr
      namespace: home
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:4.7.5
          ports:
            - containerPort: 7878
              name: radarr-port

          envFrom:
            - configMapRef:
                name: common-configs

          volumeMounts:
            - name: radarr-configs
              mountPath: /config
            - name: media-root
              mountPath: /media

      volumes:
        - name: media-root
          nfs:
            server: 192.168.86.10
            path: /nfs/media
            readOnly: false
        - name: radarr-configs
          persistentVolumeClaim:
            claimName: radarr-configs
