---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pihole
resources:
  - namespace.yaml
  - web-secret.yaml
  - common-configs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
