---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-configs
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pihole-restored-pv
  resources:
    requests:
      storage: 2Gi
