apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: web-secret
    namespace: pihole
stringData:
    password: ENC[AES256_GCM,data:TGL2vWhKeZX3watJdjJvLUXytwY+y/YzZ9FUw7z6N8hLGUxPbhbG8NM=,iv:cmtNfz6fLnYAyekDB+RgXT2Qbhq7OdGH5cXEmFr9pAU=,tag:GikHtA3Dk+E9hje9v8m3FQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dWprMElCR1FLNmo1Y29B
            c2pwbmNaVnJlYkJPY29sTzl3RTFFZU1Tb1RJCm1IcU5zVGlNdmYzWllRdVFJN2p4
            WkJaRyt3dUQ2c0M5RnBPVWFmRCs2VzQKLS0tIGZ1Z1dXRkhjZVBaYm95MDl5b1lr
            Nnp4ZzNtdkNKVnVyc3p5V1VJTGZ2aFkKNeLlbSEOWuPs9dM/jnsShfKVdwdyJYya
            0ZhfqBE8tRjbQW92loIQfFnaaFui+JccLDIE+PURTiwSm2UFBE/aAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T01:22:23Z"
    mac: ENC[AES256_GCM,data:pUgSGhwqasB1rTNVUyab1sbKmUy0B+Dz5e5BE6F9W0muCvikMnG5lt2hIvn7Us9UfJIiRzVCDEDL1IKAhlIQsuxOGdRqpne5EoZC5nw9Lfv2H3z1yuCn5cqURIsYAXlSTkUHV/UrVQY8tEy7bUGinqmb0l30axC9HXjOWRW3A7Q=,iv:iSDHOSxRszCLpzqsHhYQzoBCDMbfYUSo48yLKmfNC8k=,tag:DXK5lrwbIXgE2oRGRgZwFg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
