---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-fellowfreak-dev-staging
  namespace: home
spec:
  secretName: local-fellowfreak-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.fellowfreak.dev"
  dnsNames:
  - "local.fellowfreak.dev"
  - "*.local.fellowfreak.dev"
