---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '26.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 24h
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: helm-values.yaml
