apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:NtjJ8uQjSM0xGb3g9GFiQ3c4IqdTbHVnxio7MUMkr07YEyMmjHjVHg==,iv:WbHCaRcglHLaW6mYt5pdUcOnUbKNKAbTFeViKJ5n2sE=,tag:kdL+ibVlv3O4ugNd11ZNoQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y0NXdmhhK0xBTWhaWXVI
            d1FnLzJwQVhFR0hHczZpQlN2aE9kT0F3NVEwCnRQWFZPVFRQMmJRS0dweU4zMlZu
            YURjZHJEZUt4T0t2RHdRM0p1MXNqZG8KLS0tIGxONkdPb3VRU3IzOTJRb29mMWpO
            WnpsRmlnb2VHaHFKc3Z0dlltZTh2TUEKxbhURhbA/G+s29jki440jsflXPp6z2Gd
            loXHeD46LGrKKCrZJ0xBl77vFwcwx2pgGTNjIA83eJL+CuNv+OrEsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T21:00:39Z"
    mac: ENC[AES256_GCM,data:hL7VQUZnDAK1q8k/yzUWgI51qYhVUt6AvGzx3UTDnafyvhqd560Wum2Pqgc7WbnGV9ASC1g45VtOjDnq0dCCPlvvFaxssjRgx/ADPUxUa8y+z7mT9QDLb/bhgqsJ0lCZqFLZP/mORKcKqvM6rkiGX6v+qNJaSNLlVa/ut+5sHiM=,iv:sYBBVwmV4R+xbYMLbcL6X/qaype+aBErgYZj15nq4bM=,tag:teRus3EzxLbPWPwQkJQevA==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ/9EaZhyw6B2HGZPQMoxM7T9szeOGeoWV8s/FoAucxpGdPV
            ZZkAvZgMNOMUvbwMrMLtSFtZS9oPs8b5e+ABLAi62dQ0Uwr7660a6fO/+IiCYmaE
            uBf8jrMp8Go98rpgrgGRTBK+seqQszA0vh1JlxPocLLpoivWabbuV3Q8WGPFb0Qs
            QXbPnHjmQyZ0qLgQxJh+DproqftPyuPS4fCfxUe3azoem3p5VXw2erUJR2fyuAt+
            fJHdNbcPokt84YjnHsWKFkHsgzY5NAXum1drHStrYqSkFibmyo3r2L2VefYs4YOE
            IRqMiUYcK3u12hRAm4SF2IX355qugF3oUOSYg9GKgRzaSbH2nx/BznJMlH3YO8FZ
            /KVdk0JqMp5xBjsICYHO0ETNwsyJ/BsGecFpgf4fxd2lugk2NgFHmDHCF9zQQccD
            fk/o9TNsL0jK8xDAmGY3KF97Bn8z8P29UvbT2Vf5/Yn4zNVn68ya7IMwV8QlxoIZ
            BT/wFU+fcsxTtwOM3eqiza6pjZNcGIfNFDaneDu3LQ5oN1MAJMw7xrzJr0zNghp5
            +3Il9EC4Tzfrt3zR7UdrYmugMGCSUksaKRpI4UjZW57Rh+1dYoKnHy8WDfC1Ohaq
            XY3ABYj7AFrRzNmJVRv1NGlPNDNJ5xESlpKgUDvrWirBU3e4o871RYXG3Ho2dKvU
            aAEJAhB8vAzs9amjwgPy/4bPipJw/EkcdwYAUxRa6fFzK9jLT7QSfD2Wzz6pYg5T
            WgOoOZd1e5Psl9scEFQiOnqnq2TxMrn1wyDFHbrwN5KdzhmpLP3fii6T1rfQK1i+
            SQglcC9JV9Sh
            =WP6S
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
