apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:NtjJ8uQjSM0xGb3g9GFiQ3c4IqdTbHVnxio7MUMkr07YEyMmjHjVHg==,iv:WbHCaRcglHLaW6mYt5pdUcOnUbKNKAbTFeViKJ5n2sE=,tag:kdL+ibVlv3O4ugNd11ZNoQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOUlVMGlENUtwYnI5SFdF
            WmtYZGVtNXFVNVkvWHFMSWkwU2ZqQzU2aDN3CkhCRXg4MXdTeGVBSlUyczRHZXFI
            RjhMTGZadG4xQkVldHF5RzhNOUxpN0UKLS0tIFJEandtK2JscmhKTFkwYnFicE5u
            Q3FyZjhXdFJoUm9aUFMwaTNzQkY5WjgKJDpKlcgSnH2S4TBlpJQ02SbEry3LtByJ
            dKBP887huYatZRl9ufD6bV1W+lwVxPUtCFn6Q+JnCa7vL1FVgEHADw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T21:00:39Z"
    mac: ENC[AES256_GCM,data:hL7VQUZnDAK1q8k/yzUWgI51qYhVUt6AvGzx3UTDnafyvhqd560Wum2Pqgc7WbnGV9ASC1g45VtOjDnq0dCCPlvvFaxssjRgx/ADPUxUa8y+z7mT9QDLb/bhgqsJ0lCZqFLZP/mORKcKqvM6rkiGX6v+qNJaSNLlVa/ut+5sHiM=,iv:sYBBVwmV4R+xbYMLbcL6X/qaype+aBErgYZj15nq4bM=,tag:teRus3EzxLbPWPwQkJQevA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
