apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
    namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:ETBJGFo6abhdm8RgvF4JlOz6NVEyL0Xu,iv:cdkopVhJkGykNlDeBX4Zdd3dIl6YSSe1mVjkHOt8/FU=,tag:r2YIa0QK5Ss97i+ziGFEmA==,type:str]
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:cHAwwYc4PMdYBZRIdf7ZuAfglxKmWj2m,iv:Jprh7yI1DyiSx6HlEwEz1g+zQ+97wgwMPFS2XmDcfVA=,tag:pvSJj2D2x7YihybT6wgUMA==,type:str]
                    apiTokenSecretRef:
                        name: cloudflare-api-token-secret
                        key: api-token
              selector:
                dnsZones:
                    - fellowfreak.dev
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbUtDK2NTRGw5NGx0bzN4
            elRBeklMVUlaVUVvS1lEN2k0aVRZWDFydVVJCnZuclN3NEhYUWkrb3EvUkVVbG81
            NEFvUG0rVGhyU3VTeG5raWtyUS9UWlEKLS0tIFdWRk5vWkhFei8vclA3RDdzYkox
            OGtEcmtYOTZFWFh5RDE1OEVSWkFqVmMKTWs3yOS7aQEBTL8YdkH1rES+E0eAscvs
            iSzNBYMh/4r8Xzw3u9LJ1yLtYZeF4AnYO0XlZv764OoTHehnvwUd3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T19:53:50Z"
    mac: ENC[AES256_GCM,data:oCFBFKbVXqjOKRq7fLCKgtoeWfMQYTEAqu3zhyeoVLFfCw83ZGoWczqk/pLtIXy3K0/mcDPYrzvq9kp5MAI23nfjx5qgWHITYTUycYkvVbW2YvEXFNaD42Vxz4iFJ684I/BjmJYY7YSj4zcv0WJ/gYsFfToJWjoof1/MB3Y7mE0=,iv:J2OnoNVwLDyLBNrk6758rPTDX4dXy0cMItHV/Ou2rQg=,tag:dw1QWkovBdb5oRNeU0KHEg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
