apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
    namespace: cert-manager
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:GKs0S8KDE3ruFYG3UJcF7clL4xLYIvt4,iv:W0yymKm+UVcx/iYZHbvyhSJQG2yMYRL0inRoR9fVrHE=,tag:Y0FTnvwBiSsEvck6l8Fr7A==,type:str]
        privateKeySecretRef:
            name: letsencrypt-staging
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:12rTMAxJRHHolsNGjY8R1LtegWNTKyaY,iv:VXg7cfImpop9UVuN2uTgGAUC8B5to2rBEUgeVSMMrFo=,tag:k6k6OGDxwnJmfcTbGBCQwA==,type:str]
                    apiTokenSecretRef:
                        name: cloudflare-api-token-secret
                        key: api-token
              selector:
                dnsZones:
                    - fellowfreak.dev
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIblFMcU5UWkNzclFDVmVu
            MkNUc0pKR3ptekhkMzRlbmp1VmxQMkhkbjBJCm90SFRwUEhMYzgydGZ6ZHZybkRs
            N3k5WlBKSGRKc3QrT3lnVWE5QXlBZW8KLS0tIEV6SlQ4RUdpakdXT1ByejNoRmhG
            cHAxODZ4SUE5anJXcGhLejM0ZzNPcjAKtVZ5IKoqWHSHZQ3UO7LkXfdRV7hLvdjF
            BrAZDwA9XV6lUzIp2Z5g2yR2oWsqBSvmQz0u3Qq8o3GsXQ4tXmFDXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-09T19:53:32Z"
    mac: ENC[AES256_GCM,data:ctazPITI+WWfaPgXfIN1DOih4Uw89r/39ptCxoulwLEYx1nyuzQgVd8O+BPp0EA8kSHH3CbtKw+vdYoOfjq6Khpt/4t9ig5cOgtTczKvi4/xTkbW4vYVibCVV471BRNwUc29WUgci0s+Ac9+QZ4svO/L4dOxgSc44vjEv1C6FvQ=,iv:NJtXaUUyicDwHdy0tK5+pZ+5boCIGDapwsWXlPDp0FQ=,tag:Onlt9L7l01Xedc/z2U3HdA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
