# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sonarr
#   namespace: home
#   labels:
#     app: sonarr
# spec:
#   template:
#     spec:
#       containers:
#         - name: sonarr
#           resources:
#             requests:
#               memory: "50Mi"
#               cpu: "150m"
#             limits:
#               memory: "150Mi"
#               cpu: "300m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-4k
  namespace: home
  labels:
    app: sonarr-4k
spec:
  replicas: 1
  strategy:
    type: Recreate  # required for ReadWriteOnce pvc
  selector:
    matchLabels:
      app: sonarr-4k
  template:
    metadata:
      name: sonarr-4k
      namespace: home
      labels:
        app: sonarr-4k
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.12
          ports:
            - containerPort: 8989
              name: sonarr-port

          envFrom:
            - configMapRef:
                name: common-configs

          volumeMounts:
            - name: sonarr-configs
              mountPath: /config
            - name: media-root
              mountPath: /media

          resources:
            requests:
              memory: "50Mi"
              cpu: "150m"
            limits:
              memory: "150Mi"
              cpu: "300m"

      volumes:
        - name: media-root
          nfs:
            server: 192.168.86.10
            path: /nfs/media
            readOnly: false
        - name: sonarr-configs
          persistentVolumeClaim:
            claimName: sonarr-configs-local-4k
