---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/conlon/homelab/fluxcd/clusters/pi/home/sonarr?ref=main
  # - ../../../../../homelab/fluxcd/clusters/pi/home/sonarr

nameSuffix: -4k

labels:
  - pairs:
      app: sonarr-4k
    includeSelectors: true

patches:
  - path: deployment.yaml
  - path: ingress.yaml
