---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../../../../homelab/fluxcd/clusters/pi/home/radarr
  - https://github.com/conlon/homelab/fluxcd/clusters/pi/home/radarr?ref=main

labels:
  - pairs:
      app: radarr-le
    includeSelectors: true

nameSuffix: -le

patches:
  - path: deployment.yaml
  - path: ingress.yaml
