---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-configs-local-le
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
