---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-le-configs
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
