---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr-le
  namespace: home
  labels:
    app: radarr-le
spec:
  serviceName: radarr-le
  replicas: 1
  selector:
    matchLabels:
      app: radarr-le
  template:
    metadata:
      name: radarr-le
      namespace: home
      labels:
        app: radarr-le
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:4.7.5
          ports:
            - containerPort: 7878
              name: radarr-port
          envFrom:
            - configMapRef:
                name: common-configs
          resources:
            requests:
              memory: "100Mi"
              cpu: "150m"
            limits:
              memory: "250Mi"
              cpu: "300m"
          volumeMounts:
            - name: radarr-configs
              mountPath: /config
            - name: media-root
              mountPath: /media
      volumes:
        - name: media-root
          nfs:
            server: 192.168.86.10
            path: /nfs/media
            readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: radarr-configs
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 2Gi
