apiVersion: v1
kind: Namespace
metadata:
  name: datadog
  labels:
    name: datadog
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 24h
  url: https://helm.datadoghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: '>=3.38.2'
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog
      interval: 1m
  values:
    datadog:
      apiKeyExistingSecret: datadog-secret
      appKeyExistingSecret: datadog-secret
    clusterAgent:
      replicas: 2
      createPodDisruptionBudget: true
