---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 24h
  url: https://helm.datadoghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: '>=3.38.2'
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog
      interval: 24h
  values:
    processagent:
      enabled: true
      processCollection: true
    datadog:
      apiKeyExistingSecret: datadog-secret
      appKeyExistingSecret: datadog-secret

    clusterAgent:
      replicas: 2
      createPodDisruptionBudget: true
    # tends to make cluster unstable?
    # toleration(s) needed to run the agent on master nodes
    agents:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
