---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress-route
  namespace: home
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.local.fellowfreak.dev`)
      kind: Rule
      services:
        - name: n8n
          port: 80
  tls:
    secretName: local-fellowfreak-dev-production-tls
