---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - telegram-bot-token-secret.sops.yaml

components:
  - ../0-components/health-checks

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 5678
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 5678
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 5678
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/path
        value: /healthz
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
        value: /healthz
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
        value: /healthz
    target:
      kind: StatefulSet
      name: n8n
