apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: n8n-telegram-bot-token
    namespace: home
stringData:
    token: ENC[AES256_GCM,data:BIQPDhlReQI3rh9DrHjIAZC5xgijVoxXMSKwKmpd7v9P04YDeciMeqzyWuZDaA==,iv:qEJfY2RKpBb/kemgCk1r/uVetqF+P2RoQWm89xobG7E=,tag:tjteKhA2Pa3SNXyJzV/Ztg==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWjQvSGdCTUFMak9ZZ1V6
            em5leHE5Rlk4alliWHNPelVEc255aE02U0dBCkdwNkFUd1kvaUZXOUwyUXg4VUFI
            d3FGUEFROE9YNW84QXZvb1EvNzJvTU0KLS0tICtETnhxZkRiK1djVk94ZDRoZWw1
            MnE3NkEvMWZYUmNsV1NiTnlHTXNhWlkKpTT0C6BCZf847DOrcyJHmPtKYGCjhHf3
            lf6gh9wBqzp49z0haLEILpzMS9g3TOGTsZSdnUjqe59omiiMbzuLyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T13:18:38Z"
    mac: ENC[AES256_GCM,data:z+ry6WcDunpyYOBy2speCoPJecHsGqoh3tO57ZNXuelawbj82qmTg7TzFKZWZjORZKElQXEi7oezjcgD3LDD9pwGrIuDjcn/KUTKcLPCvvDCXK7feimTqrjv3gxXQYy/W9klAdedUD8Iv0QN+wQtA23URxpp2g9qOx67nitZJKc=,iv:30fXcDRnN8ZLpr0d7/NSR0SqPBtpcAYEVKNd1tWyTeI=,tag:G+AeFM1m0ME3UhBDskTVFg==,type:str]
    pgp:
        - created_at: "2026-07-15T03:44:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ/+OL504HVXHgNNxtDFvCPsVgcCvXaiViKiv0dHzj1lGu6f
            prfmGvC96ar145txVWU5RpMQ+eSp0urqUiGDQYBApQv0/tIYDEg/0fb3uiX+reeL
            UU10AFyc/98KBu/NNDO68idv0ZLFPcycCtsmsMM1vd88dBE3/puY6e9pLz3c2F4v
            5pK/H9Pxc/nRE1qwbOJFhUOSDHXvGKNlNcViFuAylKDLmb/fCcA1j7zLOxJ0Emun
            W0HnK24zFIGKSwkHVAh9MYRdUjWwyxJI35h+VCGfVskH5htcmlAhfeIh1Wh1o+bQ
            bj0CWYyjo5KbgXSR69ouNJ8S3mWujnQbiKaU0h8zZX0Pkm6ngwxWTbv/P1vlJZn2
            Bd2s09eXmWwWUNAqrEAJ73z7fwsligu6fO9eRnXKjNqBJjqeDNykIVent63pBDzo
            JxI9YN/QUiysrVc/pbc3/zWDbsLlBiLNR0OV/26fajbuiAqdq4lShyUowfQUS1Qt
            aiokigHiUF8n8Ca2Tzy2fe15SYSiE47XgUrP0dFqk2elKaITd0jkBKwMTjm1or1z
            cF8ZkJqrytWTSeUkvr+4dsBwXfr1fL/5iQdWBugCJ1y+Stpu2D/THRzOqzdKz4Yp
            l6sdomhpqjpmDxuqMmDrVbQWvICf4+ijFEDIhWJNrff9Ijd2bP6OnudozXx2tCTU
            aAEJAhD1gGA9W5qPzz9Dkyeg8KvR7EA7m4sRlaB0jzK7jxBVC0I1Fpy/TxwRYh91
            KMM+yDpY7tENMAkBb8Dbcr2XKmVEGTwfzEH8Lt0VhASC154pvWsAZMCU0ny03l9K
            zXc7XpqsIshg
            =gz+T
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
