---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fellowfreak-dev-production
  namespace: home
spec:
  secretName: fellowfreak-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.fellowfreak.dev"
  dnsNames:
  - "fellowfreak.dev"
  - "*.fellowfreak.dev"
