apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: basic-auth
    namespace: longhorn-system
data:
    auth: ENC[AES256_GCM,data:T69j6yYL17PDhrxhRn98gqbonRdvAfMIUuCnzqJil0v7/jCNBXP8g5NcFWTGu0CX9cZY9FI9j7a5EuHe,iv:P2B/bXskttI7677lVJbanEaK9/ixVjNIms5ipGpb8Ds=,tag:mjiuPVAMTrHXbE3eXJQv2A==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QldMVS9CdVkxOE5YeVBF
            ZDJiN2Y0RlpSczdOYjFvcUhRUFBvcWtrQlNNCklvTGhjb04vNXQ2M1ZRdzdIVE1p
            QTViK1U4Y0toczVJcjk2Q2hXUyt2TzQKLS0tIDNzajF4N1hWeVhaa1FENG11aFNh
            NVU2VWpSRjJETldmN09YZHhYd3ZCdlkKTQ+ffzxu5iP+asQIwksidZ0CnGZR8CYP
            neyiuRLB4eYmy2cHm+ZPlwhBnd6Fp2J2gf29WVSatx/4GfbYmdrviA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T05:57:45Z"
    mac: ENC[AES256_GCM,data:y4BZqKGPhJosmY9n8iWbgfHyLO9dhT2hy86ZDNRhSumS+bDJPaUxh4oSScV371tOLnCZWSk5eUA4aq8ZKGd58Io67nEHHj1zmAAKmPL0JQ67PpDgmRIKruyKhGqeKXeLPetZlaHkielbEWYDIE5Mv9kvNW7SQsJHGQX+XKtj/HU=,iv:uMCmdTAO40G+R6whMq2ZdX5Vd3zofms738R67kXTaV0=,tag:g6TpRR3mYjZuRfJR2BQM7g==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
