apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: basic-auth
    namespace: longhorn-system
data:
    auth: ENC[AES256_GCM,data:T69j6yYL17PDhrxhRn98gqbonRdvAfMIUuCnzqJil0v7/jCNBXP8g5NcFWTGu0CX9cZY9FI9j7a5EuHe,iv:P2B/bXskttI7677lVJbanEaK9/ixVjNIms5ipGpb8Ds=,tag:mjiuPVAMTrHXbE3eXJQv2A==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFNSN3BZdkp1RjQ4b2F5
            d0FJbmFEU3JOeVptLzFSekd6OTVTUHlVWGxRCkJETnkxWmNaV3dpUllkKzdwSlJK
            aFIrek4rRTY1dGE4K2M0QkxJUlVZUkUKLS0tIGxSNHUvVXpFRkJadXhxWE9Ra1Ny
            eFBKQWFsb3A0U1Y1MnFRL2JlTmxYOTAKghHr69LMEJT1DqAz6WpClee+AcPN9Ld+
            MGoYntj51aWr/9TNQPr11SfhdHw4+diI8z3XyuYKHPCHOSWCwodbsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T05:57:45Z"
    mac: ENC[AES256_GCM,data:y4BZqKGPhJosmY9n8iWbgfHyLO9dhT2hy86ZDNRhSumS+bDJPaUxh4oSScV371tOLnCZWSk5eUA4aq8ZKGd58Io67nEHHj1zmAAKmPL0JQ67PpDgmRIKruyKhGqeKXeLPetZlaHkielbEWYDIE5Mv9kvNW7SQsJHGQX+XKtj/HU=,iv:uMCmdTAO40G+R6whMq2ZdX5Vd3zofms738R67kXTaV0=,tag:g6TpRR3mYjZuRfJR2BQM7g==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ//f0G2B4dFvx/svn6oVS2u69oVEF6fc9fyxupc5030Mssn
            MWG1Fi8e8MnqDNZGSwLMw06ioBBO3b+XnxLb4eK6+30nNhtIRW42AD7gxHUOaaHA
            GH2z0jNE9F2CR+l67blrx+LIJV9gRdLkzmBGdH1zNtJv0jWGfDw+cgKA4Dba5fun
            ZRMhAl614kvkxtv/xunWu4qs7WWIk7kMtISBDE8PTavikmOiAlASYqdTVGULNTNW
            qTrLVzEp8NZ+djAaIU3L2+kZfRapK92ndJU495bGj6cvpGYNkEyuu/byQVkHk2Y6
            qKdLZatGVz9VtHEYeNN2hxvtQtkCj0LVEV5GDv+ixpr+th5ZfXTIQZ15pNwFW1PN
            41uY+Q59SL8gzxuZ2mIku+pCrPR6x82FeziReuTzrBiDTPe5Co6/iWUgYhxENxh4
            YV5jLR5jLpyZTKFO4GmPtfvoXJeLtU9yGGrYm7/x3aakeTB/QVWjlW2LvwzUg+Tb
            j7ydRJZUGFlZb7se95D8SF+uR6j6ymHc5HOjk8FQPzuwqEsKw4NF5XvcmrtTQDuO
            03I7zgCQJStsxcZpSpB8CKl5RXon3g1L0dnqVX/CCzD2G6Hxg03Zk2DmeXupsMxA
            Y00wjr1pzPtIlJYvdRut9pzqHjRx3U6Hy7ALXOY5z9pRR6LKm4KuhIfwSqgYyzbU
            aAEJAhBBf8rdJ0Rq9fwiEk9FYL3jjYR5+4r940oTbQSZdtlykPVJ+dPhpEa+emxC
            yArZ80J3HgqVvPqhano6qGRMkj/9rIOakjQtO4gMLzP3oPwYDIo5KYQLM89Ny3H/
            1zuiOgycfgAs
            =zxnG
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
