---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.5.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 24h
  values:
    defaultSettings:
      backupTarget: s3://longhorn-recovery@us-east-1/
      backupTargetCredentialSecret: minio-secret
      storageReservedPercentageForDefaultDisk: 10
      taintTolerations:
        - effect: NoSchedule
          key: vm
          operator: "Equal"
          value: "true"
    longhornManager:
      tolerations:
        - effect: NoSchedule
          key: vm
          operator: "Equal"
          value: "true"
    longhornDriver:
      tolerations:
        - effect: NoSchedule
          key: vm
          operator: "Equal"
          value: "true"
