apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: home
stringData:
    db-password: ENC[AES256_GCM,data:In/Un1Nfw6D4vhplz7iOKCZUz0hFMLbukj/uErDNwu2YMg==,iv:pxIxgFeMupSJP0sYh8E50Vv/jEg++FO5/9wSz87pfqQ=,tag:Hko3rxG70g+hcZZ2eGrOKg==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZkpZWllIK0R0NHE0WmVj
            QjdFTmRpUjhYdlZ1cjJ1OXlPZ2N5dEkvOEdZCjFkVktFUS85cysvUnFlWEFzc2pY
            YVErY0I1enBzbUNUOWdxUzl0a2lwM3cKLS0tIGRjbzhJRnFnVm9pNzVERHM1M2l6
            NVluYXA1OWdCVUpyNzlZZVRkQUpvaEkKJ01GOGq9wGfl1+Dn9XlnKtQpLD+wsIoZ
            Tgo/hW/z8AoY+gOs2C6OAvG6MAxjKCopR17633B+to9VCcRJ+U/Mng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T20:54:24Z"
    mac: ENC[AES256_GCM,data:p8LBx4hy9ckch+LTMXPM3CieSPxsO1bDxkLU8U1XwAOANrseROmJlYggZclzJTCdHiJs1ecR6x21jzVEGOu7mFCrpTseRCwkgkPjpqCqcsaQRRY2Y4YfOjK00LYtumOzNwJ4gWErEYIHsK2JM7F2M9R5d1Q1pwqGBf0zl4LFGkQ=,iv:JmQkkNtLPbziaRkgfhSXep4n1PhNLv0rrEbGBCG9/hw=,tag:FQ2lZ6H+9L4s0rtFhlKNHQ==,type:str]
    encrypted_regex: ^(data|stringData|email|password|DB_PASSWORD)$
    version: 3.8.0
