apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: home
stringData:
    db-password: ENC[AES256_GCM,data:In/Un1Nfw6D4vhplz7iOKCZUz0hFMLbukj/uErDNwu2YMg==,iv:pxIxgFeMupSJP0sYh8E50Vv/jEg++FO5/9wSz87pfqQ=,tag:Hko3rxG70g+hcZZ2eGrOKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-15T20:54:24Z"
    mac: ENC[AES256_GCM,data:p8LBx4hy9ckch+LTMXPM3CieSPxsO1bDxkLU8U1XwAOANrseROmJlYggZclzJTCdHiJs1ecR6x21jzVEGOu7mFCrpTseRCwkgkPjpqCqcsaQRRY2Y4YfOjK00LYtumOzNwJ4gWErEYIHsK2JM7F2M9R5d1Q1pwqGBf0zl4LFGkQ=,iv:JmQkkNtLPbziaRkgfhSXep4n1PhNLv0rrEbGBCG9/hw=,tag:FQ2lZ6H+9L4s0rtFhlKNHQ==,type:str]
    pgp:
        - created_at: "2026-03-15T20:54:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDAQ/9GsbZqxDVEaogTVZvL5o52IIGscuZGURXWWnE0/ilI3Ta
            g6tgRxqg68/An5GH/1KcAM9Anun7IWe8WmFJpWNh1hEIX2gbtiSTYxtsFgM7Y+ZL
            pciqmjMzJZUIVETE6QJcs4/+0xPL8h4xTZSCG+6DN4re1hwb0DnCCzRLYt1dL0NK
            O/1zSWF4M0nrnshkL5EpWYGGJJlCAotWinqEGHSWFaAftIyXGtzQsiFap6y12oHk
            o4mIrREeOHYoJRICLTsDxPMBVOZp490X64hpG5WuUivZUOKzAi5ub0pYEeI4d11U
            5kgxpGsB+AWuPmQD6AVEsB3awwBWvqRHZFLDdavu1eSZnrazZ7VjoJPKf9fOQqy9
            kjxzvYN/EQA4WzKuVIic5PD7BHNmehDwXvpCAVH2OkiF7zUbqXALh0Ae9g8W/0UB
            ViJ3OtFhJgnHqOq/wf+T4GTxre+f1YkhOwnMw4+Jqe+9W9UXWbzmreyMAoa/XkXb
            IpwIEypUTsTsLbhO8ognNwm7ahYR0dgSNcHh/cRvH5kHJCWrqrvuKnYwVJhP6PF7
            H5RH4+o8Kz1fRAXe7w3n4meZp9BD+1kp7qcn+P+LY35HZezREvL90Ocd/K7/enpH
            a0pGFFB9rcCcXBbPUpMGcFeH5VyHCGf6iJ5GcmOx9REn8W0O6qDJrvP2IS2Swf/U
            aAEJAhDpllqMn7kM4yxYjBYKunQw0Tl+TPJMoSxRKfRTRXjINmH6A3+vvOUAOvWL
            Eo/YS4YTWFC7cPmPDtBZSqA6GMUEP/3y9ZLg7b/b+Y44u6OZTmBw+e2terV2N4RU
            wIM8ka2zpK/f
            =5OEx
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(data|stringData|email|password|DB_PASSWORD)$
    version: 3.8.0
