apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: home
stringData:
    db-password: ENC[AES256_GCM,data:In/Un1Nfw6D4vhplz7iOKCZUz0hFMLbukj/uErDNwu2YMg==,iv:pxIxgFeMupSJP0sYh8E50Vv/jEg++FO5/9wSz87pfqQ=,tag:Hko3rxG70g+hcZZ2eGrOKg==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYVZPL2hZQXY2ZGNYemsx
            R0lBL2FqMUtkTEY1Nkl1T3V4TDc3UUZ2MW1JClpRZUlGZDUyaktwUmxETEV0RXJF
            L1MrNjFEMFNsalJrTGE0eGdpZXpobDQKLS0tIGpMUTB3dm5xejNVMlNoMEg5aWhD
            eEpJdW91WXlQR0QwZW5vR3JTMkhpWkEK8LY+3S9TDpnnvFG6xh1KIctdftZV7eV7
            4pKV5r4dW95SiTWGHs2NdZUPoDeCvbIyFO64OUb6oXIwtMnMnCVNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T20:54:24Z"
    mac: ENC[AES256_GCM,data:p8LBx4hy9ckch+LTMXPM3CieSPxsO1bDxkLU8U1XwAOANrseROmJlYggZclzJTCdHiJs1ecR6x21jzVEGOu7mFCrpTseRCwkgkPjpqCqcsaQRRY2Y4YfOjK00LYtumOzNwJ4gWErEYIHsK2JM7F2M9R5d1Q1pwqGBf0zl4LFGkQ=,iv:JmQkkNtLPbziaRkgfhSXep4n1PhNLv0rrEbGBCG9/hw=,tag:FQ2lZ6H+9L4s0rtFhlKNHQ==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ//XlOxFr8RXv/ohy+M4YuWqoY5c5+rYRHE1heaAk4pe48C
            O46HZXPj45sEo/QapIjWjf6j6cim8PNUjwvvXjx/ZVDREPq52bY6leRsf+S/PzWB
            SpeW8lQBU+PewsvKRaA1YGIKsewP1gE9aHnEG5PegUqq8s9O2QG+QPOiX2NgAGy4
            ZVpQ8BecUeK9RuhqgmeNNlQCr8EzlalQ+Mvi4lJUR/6PxDTrqQlwBu8iOYybQ//X
            +O8zTYIn1kLnc/Sk/cOXBV2mkotHcrMWTEpL7/FM+3/ZAtrfBXprAHN35QFIHH8D
            3Ppeq6GX2ttuIdZALrYAsmCYG9VOoO9gwt8BMPfDq3GBZGsbk7WwWkvBB9Qa3EYB
            0h4zADjFhVAiK/1EPEXcbMEQ/TM6HIia4v81MqOInGDL9e5monfWptIgTmtc2rOS
            BaYIcCC5esyqkGZU7R162aELD3W40G7EAL23OiayLmc6kZXvI9mFtgNk9+Mmfs8G
            Zf4nV/exn6YvUF+0NcNZ9k/CEYUAK5H3OHdmm20XMv7st0hBcNFGGnBXlcqF3Kge
            1hX2ETN4eJo37SAuwX7cnACFN7s8dWZgjp5WpHOSZKvDrwaNdoG0nlYpc15JyCA7
            a6+63SSDPng6EqEnJz8GrSt9S1hG2dymvH/8CMDJw7wrkVskeKKXgSPBqCEXCU3U
            aAEJAhAasXkp8rFVeIPnZ0i0GsaHJSTTmtv6kxhJcs0hZpxT5+D+FykCHVwgrCTH
            DkbC/aVIiYxsuGUuhl+COBjwlxy+xoZIIOxPO+y1/HORrrcNSTA5K3BqiAEpLHTn
            MvcUoujgZ8Oo
            =iDfB
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData|email|password|DB_PASSWORD)$
    version: 3.8.0
