---
all:
  hosts:
    k0:
      ansible_host: 192.168.86.20
    ava:
      ansible_host: 192.168.86.7
    n0:
      ansible_host: 192.168.86.26
    k1:
      ansible_host: 192.168.86.21
    k2:
      ansible_host: 192.168.86.22
    k3:
      ansible_host: 192.168.86.23
    k4:
      ansible_host: 192.168.86.24
    k5:
      ansible_host: 192.168.86.25
    kami:
      ansible_host: 192.168.86.8
    kyoko:
      ansible_host: 192.168.86.9
    n1:
      ansible_host: 192.168.86.27
    n2:
      ansible_host: 192.168.86.28
  vars:
    ansible_python_interpreter: auto_silent

master:
  hosts:
    k0: {}
    ava: {}
    n0: {}

node:
  hosts:
    k3: {}
    k4: {}
    k5: {}
    k1: {}  # rejoined as agent
    k2: {}  # rejoined as agent
    kami: {}
    kyoko: {}
    n1: {}
    n2: {}

vm:
  hosts:
    ava: {}
    kami: {}
    kyoko: {}
    n0: {}
    n1: {}
    n2: {}

nas:
  hosts:
    ava: {}
    kami: {}
    kyoko: {}
  vars:
    # https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#how-variables-are-merge
    # default group priority is 1, whereas any higher value gets higher priority
    ansible_group_priority: 2

proxmox:
  hosts: {}

k3s_cluster:
  children:
    master: {}
    node: {}
