---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-configs-local
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
