---
default_packages:
  - vim
  - jq
  - htop
  - nfs-common        # for general nfs access
  - dnsutils          # for debugging dns issues, nslookup, dig, etc
  - wakeonlan         # for waking up hosts

default_aliases:
  - alias: ll
    command: ls -la

external_wol_hosts:
  bit: 50:eb:f6:cf:2c:c1
