---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: twingate
  namespace: twingate
spec:
  interval: 24h
  url: https://twingate.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: twingate
  namespace: twingate
spec:
  interval: 5m
  chart:
    spec:
      chart: connector
      version: '>=0.1.21'
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: twingate
      interval: 24h
  values:
    connector:
      network: 'conlon'  # single quotes only!
      existingSecret: twingate-secret
      hostNetwork: true
      dnsServer: 192.168.86.54
