apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: twingate-secret
    namespace: twingate
data:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:CJRubuFZzhAFSBnzNdvUF4prPAqCF+1ZT62KdwOaYSbSjRtPhyLm9jmDLgmWnB2op13q7jMGTIqKPzy+/hEHhaJWoZXRixX9NREJ5m/p4nikoyWBPyuLiQxUk7kFKMgAZ4rYBgm47Lp3RI6+YDqBVhgXBt6W1UpiJhdQ7MyxFeBkKAay+e/3uL2oskoZfRSXzDOyKWYp3vAoQMZ6mi3UZeYkC2tNiEX3b3DEICxxm72kVOYSvl052Eik42Vl331RR1kkc7iwxgjZwjM598klmzq6Wu4CCInkRPExs2V5gG6ac908AQspv6pmDQ72Bs1c5YLW4VG1lK+DIFge6zpQCmQOvaZhqdJxSSLdwdItbulxJ6FlB6g5qeRe2bGL0PPkk4TXYPOjwnasad03yoneZtpcjFehH19SJdZaoqT48ZQs6e3h/VrWNbWY4qKLDim9I8pW7uNMwfzyBaqSTDjo82/hNobGjBNGrInJfvLcYZMKySXrcbdc3rUQaN9AJUYKvSMM9IaIT4w+0eM35mt/Ytywe2NbWrk0busIdn1YJazyrM/5mMuS8FuqcZT398DStJmy3YB8dQHBUbfxNKVJpgEn7yE3DmzTouTiNs72Y4IuQIPq06AKjQBXq5EBhmBLt0IRkcaBAnkRLvBtsUcu2ioedm1K5zDxjkYQeMI2MQpnj91DCgTmSl7RU42BQTStsasKGOWX/kV7ltMh/Oh19HzOx5yPM0fE/7JGTfq5CcYHMOLcQxMw52iZre8SJp4drtzG5R1i8c9fCpkVYeNvZJvU7ephVKmRln8fT6UsWEjftfFZYTeNkhol6YjXzi2zSEHHuv9A8Yr+0iUK,iv:HEKtLr1cRvIYRRYq1IgiCo24BXxOAgeB3VuT1rdG52U=,tag:mS9spz/YKg6wU3GkvT+gqQ==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:gE21S010uwycZNPViOMrSBRfIOpoDpW/2Cwy/f+b23y9IWreh27kj9MkFvlzDyyZ+YQHxCB8T5fRUzeqUgeQUEqBtT3MrkKyA4kAxlFf2ynUSRcpFavPPT3MWSXamBdpksK10NNDo2j3eZpjI6L2+ccAsAHawBUSxoJzAN7CuQRaHzT2MU5TvZSXNFGlwisKoQJmQddECBl88Mril3TJZ8BwM9M5dtraPTIP9898cgkpd2RW,iv:Bs/nu1jwzYF2O1tgnJOzexzBHeqCwvZkaZQEGoT12C8=,tag:1RTqxAkdVEGbY/Wie8Aatw==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ0RjV2xFcE5oaVcxL3Jp
            NEtibXIyRVMyY3FzRkltTGlIRmxvMGxCb2dVCjJCTCsyZG9tV25HWFFsMWsra1hQ
            RXdKdk1pK2dRdmJETEozM04rb1h5V0kKLS0tIDNFNDVHU0tja0ExcWM1b0pHUlFD
            ZDZkd1E4L1l4ZnNrQlIwdS9hV2dMY0EKjFPaqkR1+C8HwSE+OgQ/Za15ef+YKFLT
            n5mBpcBnVDUnY638ktInxX8tLPnJkk6rT3fBpX7TmkeTu0Op0tkU9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T05:01:44Z"
    mac: ENC[AES256_GCM,data:kFJhd7/FD6pxc1eruePjc7A3z5YXRa13dbYGJeNmd1Zj1pMZKremP+pUSmGNMObPNiG1PjTXTNG5tQxzo8544jcarCppLQ6sT9Y9I5kBVCVsIolzwvQuSskfMhKojgc+RT7oZYIwLNFvjPyh26OfPnrjM8jRwmXVPYj1OxFkrUw=,iv:cSyfCuxf8gj+y1dWT4GE6C7zwAdvk4NOssbO/tY0fZs=,tag:+NKKSY8mxYUlKUO04Pg8Pw==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ/+PfuhmMuYF6ktmPnnyquDZbrGPjLYgASDXfMQkRM/hJA9
            k7QCS4rlJmEswlQlB3aw6bi3rY9kzrB7n/KI3r6NbTpTeV8hO35c/WWT8y0uu9Je
            5xG1NQRjlryV6c/6Ypoq6z498FVqZHQXao8vnQARqrqITFqAT4Ccss0jEp1ObCyM
            sE10G/QSv4bPOA68Ts6wgpjMd5zRLBmH08Oo61E+PztKnngXVTRpmaoWC4KjUfC0
            ciuXRnvvQ/dDLMfSNbQ6q9mmm6JK+xOAqi1wItIU0CESIS3bWzCX4FduUDjPILg/
            KUyMMalNZfCaqjJCtmkrT/tvfYtqpJ9w3pQWWbfUjukVQ4xiPjTOTrhykpwjfMHx
            Nmg0Uxgp4Aog7WP+nHysbIxIMWRQReRI6tCrLC7Dxhhvhrzakze0Z3APDeEeCXA0
            WqSTT2xfLLeEBgzYtaQ4umYxrDbBCjIha4d9BBQd8f3kTdmP9Z2LIaSWqfRw7uYG
            b5ugZt64Qf1WCLKMreACL0ecu/wz9SVBxL4jWuZt91rdp3OndqVbWLGRdNPTRUr2
            DzYJl/RCK/Zw48FA20wXKdktl85zv6cW9Utka0ooo8KVx38Hw4FMm3UW22/bBgp3
            cVWN6chdUN1pAGRufFhgj0ZdaSPmBEa3ZoX2W0oSLQsZ3W36y5MINSnsQOdI2bTU
            aAEJAhAv0fJsyHxUhXPmhIXp22JZD59KFQ3wi7ceTCRKBfQon7AvDId3cmHXJUxm
            g6hc/e6ICJWR/k1CjcU2rHd01DTbmCxlR7zctZQenVZWnFvWWTuXKEcSDkKdpoFD
            1LA6jqYHsCBq
            =rnb+
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
