apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
resources:
  - namespace.yaml
  - common-configs.yaml
  # wireguard + qbittorrent
  - wireguard-configs.yaml
  - pia-secret.sops.yaml
  - qbittorrent.yaml
  # other apps
  - overseerr.yaml
