apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr-deployment
  namespace: home
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      name: overseerr
      namespace: home
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: lscr.io/linuxserver/overseerr:1.33.2
        ports:
        - containerPort: 5055
          name: overseerr-port
        volumeMounts:
          - name: nfs-volume
            mountPath: /config
        env:
        - name: PID
          valueFrom:
            configMapKeyRef:
              name: xarr-configs
              key: PID
        - name: GID
          valueFrom:
            configMapKeyRef:
              name: xarr-configs
              key: GID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: xarr-configs
              key: TZ
      volumes:
        - name: nfs-volume
          nfs:
            server: 192.168.86.10
            path: /nfs/configs/overseerr
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  namespace: home
spec:
  selector:
    app.kubernetes.io/name: overseerr
  ports:
  - name: overseerr-port
    protocol: TCP
    port: 5555
    targetPort: overseerr-port
