apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: pia-auth
    namespace: home
stringData:
    PIA_USER: ENC[AES256_GCM,data:PbMePm46EdM=,iv:mt4G3Ta8pDNOZFbki3Fy7jf+/48TDysFSEDzWbipFkw=,tag:yCZ+vrdM7zNwX0iy4ne+YQ==,type:str]
    PIA_PASS: ENC[AES256_GCM,data:oiNzkH/+LfUOng==,iv:e6bP4o1d7MBk46Ps9OyeHW9oXiLJMs3qd5yUDzXiKUY=,tag:pMed5UeJTK7Dn7IT+dOXXw==,type:str]
    HOME_IP: ENC[AES256_GCM,data:dG/0oOQKIbSyjkUnXzc=,iv:f7IkGKnfyZXLUck8sMosD9x75s8JhD/AZuP1hvo14as=,tag:v85noDoWn5q0PAJzQaanEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-06T22:26:07Z"
    mac: ENC[AES256_GCM,data:llZUYQAGoYt8tXnxQxzBF1JJnq/Z0NpQxZTZmK5gxuAgqJ0pDbp8VeV9A4geo0aJErw3BkP/0bP6TQ2av+qZVwKbYC3LyOxxc6rKaleVdV4DmM42Zkpm/99RbPi+7HioVMZ785wVkIcpHhbyU9h1JnLSXtRw/J2HrJHJH8uxDkI=,iv:HOyH4qpCqVFVWw2GQlUSegxtBcQAa8Z8mscHhkH9uJM=,tag:+7kwDke0dcDYUXKV5RDMyw==,type:str]
    pgp:
        - created_at: "2024-01-06T22:26:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDARAAhf/XDKitf7X9SL0EcdNusfsx9M0m/Z7wQSDsOz5fwNUH
            XOlqwK0P0t81vlJbrogQ3w68uzmeJqFIycS7wvE6/c7qTqHvw4nynByTNFFcHUn+
            TCKliKEUcqiz9CAR9ghBzLDmVLkhBpBixvU2Q8mLgnc7FRjh15C3wVxho1ZTphfo
            jC2v1YvYf4GZrpkuYUsVlhdakOJqAIHLi4NtlwN7Ha4u2KvYAVGDV3UUrc33HK6Y
            3+PpEaYJQADw9vr62y+1CwASoGxL/1U2tcRhb7oCVL5s09IFGuMQ3bMjgDEd99GJ
            FZiRmyJo1qIsK4I6CztL/NdiHhx8SD9QtJoWyfpdF4sdkiIvOoXPffSLab7cXG8C
            RddsatJkO0khoK5Kz1+2j938Ie+M5j3hF/DQkvFyYl2kP4SewLX/EUrJ+PIHG58b
            QUM9ZJ8rXO5g3+AngBWWY/M2aghzJ6IDAQMz9+VaHkUpmMVX67WBKnos8QsgAaaq
            57E3D24+twE4yd8lCGPNTdcSN5/1oV7ZzsInejR9vBZvUXvuh6toDfcpTU0Kk8qv
            kTAGMIqONf5xFo3ESHHHbkPFkYovYPAnyWqSG6rvaH6Bd5myXnSST9Vuw7UrNSAN
            di5I6U9Oq3LIJEZ/IvoAcdjMsyIv2XEXkERgkulvPHZ1yhi9vETk3MfN76qBFKXU
            ZgEJAhCsPB0er1OUIRy285Gf23d+mQTV9RdhEZnqYVR/YIy3D8vG7Xk8ben8ND46
            uP3eFpxUrSTPKrT/NF0yKjCni/i+0+alhCe94BphZjzsUTHJaJGZ5ENWuyOSL/iA
            Buz4XYblZQ==
            =puNg
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
