---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: home
  labels:
    app: overseerr
spec:
  template:
    metadata:
      name: overseerr
      namespace: home
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          resources:
            requests:
              memory: "100Mi"
              cpu: "150m"
            limits:
              memory: "250Mi"
              cpu: "300m"
