---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/conlon/homelab/fluxcd/clusters/pi/home/overseerr?ref=main
  # - ../../../../../homelab/fluxcd/clusters/pi/home/overseerr

nameSuffix: -le

labels:
  - pairs:
      app: overseerr-le
    includeSelectors: true

patches:
  - path: deployment.yaml
  - path: ingress.yaml
