---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml

components:
  - ../0-components/health-checks

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 5055
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 5055
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 5055
    target:
      kind: Deployment
      name: overseerr-le
