---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml  # scaled to 0
  - statefulset.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml

components:
  - ../0-components/health-checks
  # - ../0-components/security-context

patches:
  - target:
      kind: Deployment
      name: overseerr-le
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: overseerr-le
      spec:
        replicas: 0
        template:
          spec:
            containers:
              - name: overseerr
                startupProbe:
                  httpGet:
                    port: 5055
                livenessProbe:
                  httpGet:
                    port: 5055
                readinessProbe:
                  httpGet:
                    port: 5055
  - target:
      kind: StatefulSet
      name: overseerr-le
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: overseerr-le
      spec:
        template:
          spec:
            containers:
              - name: overseerr
                startupProbe:
                  httpGet:
                    port: 5055
                livenessProbe:
                  httpGet:
                    port: 5055
                readinessProbe:
                  httpGet:
                    port: 5055
