apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: datadog-agent
resources:
  - namespace.yaml
  - secret.sops.yaml
  - helm.yaml
patches:
  - path: ./patches/resources.yaml
  - path: ./patches/network-monitoring.yaml
