apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: datadog-secret
    namespace: datadog
data:
    api-key: ENC[AES256_GCM,data:EXiJ8hkY9qWcCLSvcv+11WiROmAU2PBt8q1SJIsnQw/ZOzkJrckOhFad7bA=,iv:VYBP9TOiFBztYdJaDNkfsappHpB7Q6rYXnU7HHSFDsQ=,tag:qOml1kPeMorN+CkPLenMww==,type:str]
    app-key: ENC[AES256_GCM,data:u6KR3ewCccbmT5lwTPaHpUQsEUrBEkzI608HQ/B8n+H8sfkFQli+2QMwzhE=,iv:wqup5I/vnXdpQO0zHtqFG0TrGVZeVgGnveRA3exmhak=,tag:+ffolMeWKj82H1gX7gV94Q==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbzNxU3BFek9pRXVYVWhD
            eWJxUTRjUTZsR1M5K3BPTkEzNnNWSnVXbXdNCmYreUNSTGlabWp1cU9YVUdyWTVO
            Q1AwcGwvMmVXbW41OURXUTdIRUJJQXMKLS0tIEJaUHVweDhJUjE4TFVkenlzNkNw
            NXhXZGlTenJub1hvVkVSYnkvUzcybFkKG/qUYWP4OdjnSluKyvjffbkWNwsd5r2E
            f+/CUFSDEmeK/kYPdBJFvtK75HxNtBl8MQGgSi0oEPQm+oYCLIGlmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T00:19:04Z"
    mac: ENC[AES256_GCM,data:z/uL2ElBMbSWg9Xb8LKRZTOMks4XEX9TbYHq4wOqM97Z8Ql91UPKWhaS8Qylk8tF3neRyRqSKe5oot3CMEk48iQr5h7GYt7WLzG8EAKY4SbRLPfiv1E5QWBfM0hg88IqCUrQcqs6QIItjryMrJYxyuoUueywQmDBGMJywTW+n68=,iv:BWV4M1hpA83X5vZ7lAWJFEV5te0wPWu4dmfWj6oUu1k=,tag:b7FldhWxJZWz2VGks+g5Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
