apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: datadog-secret
    namespace: datadog
data:
    api-key: ENC[AES256_GCM,data:EXiJ8hkY9qWcCLSvcv+11WiROmAU2PBt8q1SJIsnQw/ZOzkJrckOhFad7bA=,iv:VYBP9TOiFBztYdJaDNkfsappHpB7Q6rYXnU7HHSFDsQ=,tag:qOml1kPeMorN+CkPLenMww==,type:str]
    app-key: ENC[AES256_GCM,data:u6KR3ewCccbmT5lwTPaHpUQsEUrBEkzI608HQ/B8n+H8sfkFQli+2QMwzhE=,iv:wqup5I/vnXdpQO0zHtqFG0TrGVZeVgGnveRA3exmhak=,tag:+ffolMeWKj82H1gX7gV94Q==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc3BBdlV1QWYyaXkxUTNZ
            ODljR2QvNTRUc1FHczdSbk1CMnUzU09CMFRrCjlCQnhUMlA4b09hRWYzK0NzUVdY
            MDFodEV5MFRqUHdMM2FZZ0RrZXlzcGcKLS0tIE4yQm5TWFI2Rm9XV3FtakhRaVU4
            TkR2ZEFUQ25aWTlxeHAyMkdPTG9jcEUK3LP6YMXLXPPO/6ARZz/rR8gq2SApDcXk
            avoXBdLPCRVLA/SxUCdPnDNvfRXTp+YRDb7BQ7awLHDjO3aWbgrVsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T00:19:04Z"
    mac: ENC[AES256_GCM,data:z/uL2ElBMbSWg9Xb8LKRZTOMks4XEX9TbYHq4wOqM97Z8Ql91UPKWhaS8Qylk8tF3neRyRqSKe5oot3CMEk48iQr5h7GYt7WLzG8EAKY4SbRLPfiv1E5QWBfM0hg88IqCUrQcqs6QIItjryMrJYxyuoUueywQmDBGMJywTW+n68=,iv:BWV4M1hpA83X5vZ7lAWJFEV5te0wPWu4dmfWj6oUu1k=,tag:b7FldhWxJZWz2VGks+g5Gg==,type:str]
    pgp:
        - created_at: "2026-03-22T04:03:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/AQ//UERW+QR76wY0y9YNOoRne4ZxQizwoNbJ6IUaXpT9hX5D
            7wG1ceHCivI4smnmAW9+90780pMnEkQv+fXgFeavnyVujCs3AC6V3TVozA4QZCs4
            zFnEs3/uEG76hn60WOPokAVQ+/T0Re9k/JMON2cVRklYVVd/f9RplDXDnvVjmPbs
            t6nCC8Azf2AvTIxykM+VVRjROe1w5BWx2uURpCwar6+S6/2kVGkfp0pEV8RLXHGm
            bzbdmDIHBE2HRyOJjOiimPP5tI5eLpI12ncPrwPruI9vqnR8DkzLpw56WvyXOlLG
            m5U1k99taaBVqxENHsZiDRIgghsGf+0DTkD/kHQUid02bqCqI/s57gzAguXY2ljb
            8OjaglcZ7sfS2SDln4eZ5YiSqr9gWH1dzgN07g+naoRGy2uNdbthn9eWoNTsAOY4
            +pVBqXR2J8Ug41IOXdSeGTZceyx91/3gIBFGjHlOl2RZp+63s6VlS0L26pYKvZTW
            +1clsQeUB1vQEg5xEWnBSECM87J2IOjAlWRKHr51newGA4reL/PLi6HQ4tL6AH/p
            ZDCWOM0j/Ud2girrkGR1hgkq2sTxLbHKxnOw6jrj8/N5baOHqB/IaWg4xEWk8kzS
            CGRJchvR9B+sBpNIr88foWLMXolMGO2aN22f+s1uikhGFqRR8zVUBtHvRpoyrj/U
            ZgEJAhCmsZu0wQNzqjOwpIpDGUDECo00eRx2jaMvM0Nht/U3BKVbciKfqKYtGDwY
            +IVJB08K9fqZXsyD5Y0ChRrQdv9NAdtlAGY4Aq8tADvbfx3E6kvSTnIzrm4dmx2L
            0ld+o+KH5Q==
            =sYUT
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
