---
- name: install packages
  ansible.builtin.apt:
    pkg: "{{
      (default_packages +
      (packages | default([]))) |
      unique
    }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400  # 24 hours in seconds (60*60*24)
  become: yes

- name: Bash aliases | general aliases
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    create: yes
    mode: 0644
    line: 'alias {{ item.alias }}="{{ item.command }}"'
    regexp: "^alias {{ item.alias }}="
  with_items: "{{
    (default_aliases +
    (aliases | default([]))) |
    unique
  }}"

- name: Include aliases in bashrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "source {{ ansible_env.HOME }}/.bash_aliases"

# https://connect.resilio.com/hc/en-us/articles/360011329820-Agent-run-out-of-system-notify-watchers
- name: Increase max_user_watches (for resilio sync). Default is 8192
  lineinfile:
    dest: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=32768
  when:
    - "'worker' in group_names"
  become: yes

- name: Include WOL tasks
  ansible.builtin.include_tasks: wol.yml

- name: Add michael to sudoers with NOPASSWD
  lineinfile:
    path: /etc/sudoers.d/user
    line: 'michael    ALL=(ALL) NOPASSWD:ALL'
    create: yes
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  when:
    - "'vm' in group_names"
  become: yes

- name: Include Coral Edge TPU specific tasks
  ansible.builtin.include_tasks: coral.yml
  when: "'nuc' in group_names"
