# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   # - https://github.com/conlon/homelab/fluxcd/clusters/pi/home/radarr?ref=main
#   - ../radarr

# labels:
#   - pairs:
#       app: radarr-4k
#     includeSelectors: true

# nameSuffix: -4k

# patches:
#   - path: deployment.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
