apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - path: ./patches/sops-decryption.yaml
  - path: ./patches/sync-interval.yaml
