---
version: 3
dependencies:
  galaxy: requirements.yml
additional_build_steps:
  append_final:
    # Ensure that sops is installed in the EE, assuming the EE is for ansible-core 2.11 or newer
    - RUN ansible-playbook -v community.sops.install_localhost
