---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml  # scaled to 0
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

components:
  - ../0-components/health-checks
  # - ../0-components/security-context

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 8989
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 8989
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 8989
    target:
      kind: Deployment
      name: sonarr
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 8989
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 8989
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 8989
    target:
      kind: StatefulSet
      name: sonarr
