---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k5
  namespace: longhorn-system
spec:
  allowScheduling: false
  evictionRequested: true
  disks:
    default-disk-127143daf51e5136:
      allowScheduling: false
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 73687573709  # 68.6 GiB reserved (30% of ~229 GiB)
      tags: []
  tags: []
