---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn-nodes
resources:
  - ava-node.yaml
  - kami-node.yaml
  - kyoko-node.yaml
  - k0-node.yaml
  - k1-node.yaml
  - k2-node.yaml
  - k3-node.yaml
  - k4-node.yaml
  - k5-node.yaml
  - n0-node.yaml
  - n1-node.yaml
  - n2-node.yaml

