---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: kyoko
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    default-disk:
      allowScheduling: true
      diskType: filesystem
      path: /mnt/longhorn
      storageReserved: 21017642598  # 19.6 GiB reserved (20% of ~98 GiB)
      tags: []
  tags:
    - vm
