---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: n0
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks:
    default-disk:
      allowScheduling: false
      diskType: filesystem
      path: /mnt/longhorn
      storageReserved: 42155619942  # 39.3 GiB reserved (20% of ~196 GiB)
      tags: []
  tags:
    - vm

