---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
resources:
  - deployment.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

components:
  - ../0-components/health-checks
  - ../0-components/security-context

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 6767
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 6767
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 6767
    target:
      kind: Deployment
      name: bazarr
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/httpGet/port
        value: 6767
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
        value: 6767
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 6767
    target:
      kind: StatefulSet
      name: bazarr
