---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bazarr
  namespace: home
  labels:
    app: bazarr
spec:
  serviceName: bazarr
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      name: bazarr
      namespace: home
      labels:
        app: bazarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:1.5.1
          ports:
            - containerPort: 6767
              name: bazarr-port
          envFrom:
            - configMapRef:
                name: common-configs
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - name: bazarr-configs
              mountPath: /config
            - name: media-root
              mountPath: /media
      volumes:
        - name: media-root
          nfs:
            server: 192.168.86.10
            path: /nfs/media
            readOnly: false
      #   - name: bazarr-configs
      #     persistentVolumeClaim:
      #       claimName: bazarr-configs-local
  volumeClaimTemplates:
    - metadata:
        name: bazarr-configs
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 200Mi
