apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:FcRBd7fI+M2MOFzeL9iMz6b8uwOYmC4JUnjk56bT0Ug1hTmYltM4UlZ50V0dYH1EHSg9The8/IYE2SoIczf2Yr/b42mXeIZR7nyNU0fMMT/Z3s35ymzyWO/FYpjHFWU3VvfPawtKY0vYQDXkYDML2dvLgGTAK+saZ50TCcrfM2DGawAJe2UfC3mS4t2MbTH7MqOASc4/+pz9GKPvR4aVDswSQu6Kly5NyYde/f+DlAb2g3tU+yo28g==,iv:e4BMcOCjNpHEBfDCtxVDJKQlKib9mXYpAIIywgMapmY=,tag:1kw9rOgPhCGYeTaPXg+7eQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQT2FkYVBEdEx1cVhGbkUr
            K1NGTG5MR2pwa0xRcUNDekgrSjNrd0NjVFdzCndjRVJZVTdnYnIzNUVnZXZmRlZJ
            L1gxblVmU1Ziako2MzRzV2l4ZWNaYUkKLS0tIHZUY2FLY0hJVWRqMGFYcWhtQ0Ew
            OCtkS2t5VkZWY3BXTTdDRjRWYm5NZ2sKJxMsxkZVcHORcASHgPEs9VbMYdK5xxSx
            P9ZguDwbOq9LmmOIoas7nEJA8kLrT6HzEh+tr1ecgglfJzNwbly1FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T23:55:01Z"
    mac: ENC[AES256_GCM,data:XkxSfautabc2Cv6rtnbY1HMLwaAkG8x+3QBEhAiQBod6Tfivckt0pwuX1bXOuDl5xp7ZwsdaqReCeY0m/Ah9eNdoWCuikDF2oUkyrmALRoMa43jDgdli+uZ6btLBBvCtfwigGd0/G58XC/UDpKKbgvK3PUOnZoDmx//XPEEpMFw=,iv:7O1yV//SmWzOn55983Z4OyKRMk2wmM5m6/9svvFRz4s=,tag:0FiFFaPdrZw5nZCnSlGvNg==,type:str]
    pgp:
        - created_at: "2026-03-23T23:55:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2lsLFHyO10/ARAAphEC9v6zN4MyCJtg/sAb9SokbK08kspOM5MRoGB5Txyh
            BbdR5S2p5XpBh7AK3ubTfgm2emHCPmE41KWz9DcDVDpkhpnOPfbrBSmyzERrztTe
            AWvtd3JksM0EKuoqrTzh0GlsoqsCI4y4SyiIXvu/Yl1EkA0afA736fYVlfg72xVV
            N7sZcAPz/8WANTjRuYpPMPAxOJfy612luSR8HhVulj57fvA96ljsbjYn84SlknAN
            sV3TQy4P2EFeJEJ+kp+QkoYqtNFQGvmgLyuTqWR/13YeNilevhw9yeQl0fJPBh4K
            5DoD/ri6eOHcGyzpAqBQMzwCR9dK9iXhXosVmult47YgDZDwpPftJXMqV7iTWagh
            03LaBOoZpWpemoIV8dW2ZAoJxC5fOhyGW8cy4F5orPdyIidUB5d4pCA0oLNhD4H5
            FhH/tqUJYgkoUwfGvO/v3LNID/0Ott0w+AurbS7qZHIMzIljAOglRPX6GRyRm1Br
            J62qQcL8m4927NlGDzIcojb6ghs/b+65t7Q6HLAbMvEj7WUZWUScX0IfS2dCWEZB
            0PD7dKqzZ4Za3EWo6p+6i2aRe7Bv2VEgl0U99D3IV9vlMifc/Gw5AhwYRDplrAib
            bCLpqQcjCVZg28j5SwTgMhM1iJKeVZFpsL4uvHgCg8GkIYy+1BmrATewcenrQcTU
            aAEJAhBwVEAi/klA/V3Q8cGgDScIiPQpchbSySDnWst5LOQ8Rf1jhQcFnmNpn+VX
            1Av8qEOH5uKGcHpMNE19M8BdOZR5b2/VnM22osa8FpFNNBOdkxUik2yEpzd3INlG
            ytp4H7wge/0c
            =5R1z
            -----END PGP MESSAGE-----
          fp: B762F357A4FF075827E3A5CFB2EC35573C2EB738
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
