apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:FcRBd7fI+M2MOFzeL9iMz6b8uwOYmC4JUnjk56bT0Ug1hTmYltM4UlZ50V0dYH1EHSg9The8/IYE2SoIczf2Yr/b42mXeIZR7nyNU0fMMT/Z3s35ymzyWO/FYpjHFWU3VvfPawtKY0vYQDXkYDML2dvLgGTAK+saZ50TCcrfM2DGawAJe2UfC3mS4t2MbTH7MqOASc4/+pz9GKPvR4aVDswSQu6Kly5NyYde/f+DlAb2g3tU+yo28g==,iv:e4BMcOCjNpHEBfDCtxVDJKQlKib9mXYpAIIywgMapmY=,tag:1kw9rOgPhCGYeTaPXg+7eQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVm01dTd3c0l3eEczaDVU
            c0ZoUEJZRmEra24vZDcwYmhlekRlZURQRDM4CnNzUWRIVjVWSExTaVNSZlE3Szd1
            Ri9xeVNZYmQ1aDl4b1ViaFBoMnd2QW8KLS0tIFBpbVJGR2gxNUcvUUg2dW1ZeHZv
            VDlyb3BDbHZyZ05zejZUYkdkR2pyTG8KRmtvBtyQiY/ohcON/lGt4ugydriXTyV3
            2PKzlalVPRdbdYi+MTxwNlTBmgmiHdzgGUexK7wa2z3hMOztLbll/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T23:55:01Z"
    mac: ENC[AES256_GCM,data:XkxSfautabc2Cv6rtnbY1HMLwaAkG8x+3QBEhAiQBod6Tfivckt0pwuX1bXOuDl5xp7ZwsdaqReCeY0m/Ah9eNdoWCuikDF2oUkyrmALRoMa43jDgdli+uZ6btLBBvCtfwigGd0/G58XC/UDpKKbgvK3PUOnZoDmx//XPEEpMFw=,iv:7O1yV//SmWzOn55983Z4OyKRMk2wmM5m6/9svvFRz4s=,tag:0FiFFaPdrZw5nZCnSlGvNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
