apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: alertmanager-discord
    namespace: prometheus
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:fO1Ul7Q5uT1xcGZ0jVJf9JcK1KdZ/GJ9KsrMNZdX1Z1HS5TxHZB6Cs8NMQJPCqDe1d2eOm45ePQWAFtsYj828LjlXd4DCw2kiciuAtgr/AoFkvrLAzA6hErGX3gZepCbCWiuSczCkDFWqzqBLiScVlVM+3ecC1cgLrr08cW5UIG9diVBU5VJsMtjppRrNf7VabA37Fyj87RGq+f/lrC8lhziDLleDbj28X5rtcchhQaqQrYwNiig2cl25Fr9uQCyBaeMr0Z7MG+4OAwDrdnGkijip8JuO0q7EUwIuPQlzIbczrjQo6t+vemGeGMh7SUza9AaxeMoVN/gQICSgw6FQEvPamWI/Yg5JyeeKUdQLfzFG5I0S87VGx26XGXrBV2zjsXn/4C/qiDH9POpHaiH/6Ly3dU5nDY+gvhY1+tV7Epw7nlm+ysBJKMGQ0Z9XS27Tns9M0LennCr4Via5nsgMYNpDpKWQM7rfFHcnB8ClyLrFR2Brs7asFUpWWT4qzlGjVETkQBAnnjJuaUfIopSEqQdoep6Jo5lamxizo5/kKowQBUM8P//m3tjOvXxPvvJeDEsJ8IetdK6v0pk9kQSeNJ5ecn7Tl3HeSQUHEK7jPQgTUkI+LiCMf6szbNsL5phgPWUH2bo97HVWvrjyx1GY3/09mo2tgQwtXxtMnIFSKdTt9v8IkW+miin5+OFXnnCU7+EZhS3mzlRjPNFc0CwERkFh7UqtjUwBC9Sc5EDIglhc0Bc8NwLmdYwl5xzKGCwwMcZiYNn4Yn0GHNzb2fu3P8ESR7e5ti2xbEybUBQv4uUVvXT9Z8jGh8cb3k4HET22JmBxCkC8Ouvn5+ltU12PAP/VMO/NXVyABfHXZQ2e8URq9Bh05kTYOr4yIeoTt1ZctGUNXtd7kJa80VaHj8iLvZ4qVCnhuy6hVS+Cct2MCCzOHQQgWUH3W9vDOnxh89HIHqwaEJOqWVtpMSvSEzfr5ymSEdeSJfId6m7Lcuk4UzREcqewnbNkWSwhhvbQdrOFQK6xhVRZ++x9fqJki3K3bgtrBH2Jyd64hkOrHb3/ykJe76j7yxJkkc2JXS0iDmamSE3CuPSq/0d79MDoXqAjsT5WBiv53PmZn/1b/UU6zKnwFZIV0yC2+krWCA3k4zfzlQmqKgCSdUoJ6bYChZd+iAsfLxHD4U5tqJar/EJZUUKPR63aPly7HYzUbteg8l0sYTbVv0f3NtoHyVB61LU/BvF9I/lI/osZE5WmsB+OiQsDcxNXk6WXp1N2NLAgcCIONL5viE6be0rXJyxMCLIvPFiFKkenKf4D1Q0e85gor8QTlF/RpH6az60jPs+JmTVHUIIyuLYC5QUM+m4zVQzDQET0zGAx6iP4aexScSNGX27gdKGgdpN3gRiNbnt5L1VGg6ioV5L8cNQjgh1SULmitP4/CaJW8ZDAecvjBPZ4CRCvzxh7AVVsfTzoz8JrBwn/7J5LfKKV3mENmWRwl5Jyh8bm1kXqmriEwBQ6X2KNOLP7jaqfmEJKcUhKDaXW6PM6WK7vlarwsUC4w3gkF0v0qw3XR58IS1wWE3t+dA=,iv:nuDpHQ+6CnEExQ/KsDpVpAn6mhH88rjmOCFQITw6E/Y=,tag:hyinU31ACvmb55GfgHWE4A==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVFMvbi9zVHdCcHY2R3Mr
            OTVxdFcxWXZOQkhoZGJPWXB6NzhYMk9ibUJBCjVyd3YvaElISy9wbXBOY25aRmIy
            L2l6ZEtlWHJyRk1ackNVSUlhWnJnbU0KLS0tIEo1UVBBRHZDR1JTSmhMQWJwUlVn
            QnJrbFpzdmJuNkVIZklLcjF3VURab0kKTRkwCwsE4k9BFKb9sY21Bw6lKsianvNa
            /xqaps2nb50GpWpvOpRUfqIvgKFbnv4jfym5U++EWaR8BiMLSEkV9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T19:32:15Z"
    mac: ENC[AES256_GCM,data:eKSQVpyTA6amreCcQHXWKWN59FEZtM65/xmHle+JDAB1qIiXUUYS6e63rJSdCuvsJRPFV7mukonO2ZofgSy6DHg2kNqyQzhRcKVbJuTq/G7miilDyKXQMXRIM2kTB9fJ2yyQHDNRgNETVHT898pJqWLj+N+2pCpw3GSTOvifDY8=,iv:Hcg3olu8z/tbocClMcQj7TEfgmEB/C9q+s3DvDssNak=,tag:Gvded5Z9gw+ltk4c086JRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
