apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: alertmanager-discord
    namespace: prometheus
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:MlkOCXvQi8QZZJneq2zd1wuoBN3zhUvPYZxpbGsYuB8nATI40jdtFblsszv06IS1r0f6P6xBwaMbT5zbcK9+8my8pFaiW2ykYEQMUa6+OSw2qSHEEPy3dU1GcbM4NJOr18u3GgSO5J219H7jg2pQobZMn9mcXO5ULcuKQiu4K0nx+A8kG1v6YNwN/NVOyWtKKrECdjgAOYWBRbMsCn/LtU4OF575x8BAS6j0ZLuKeQ/6+FzYfEBl0OHPOxdxvJi78N6mk11FLFXC8+j6lr2dGE+qDqL8X2yQ9BFTodQRWeqzgfKZuHHepoFxTOYG2Y7EVAI1Kt94VH873PvJufor4wYrTcvN4iZCmARCl3vvgmKsO1pwlpgbgHg7XubP0jcS3ssWOjNRnOnjNeutuCaB7SHk6Hp/uIMWn+6J3Jg6PQCk96dWsW7hG7h7h4n1AbkB9hcTMDIAqhXG22l21mlZg4h4LY52DqDf4niLuTthgfT1Pqgi+OgI875p29HYEelnkUjkD90eef6m4AufD8RZu1DJkvRM8k2ihtP2g7M8a9zDN/XgG4rLWNEYrfrhatTK50Msg6j6NA9YJIIJcfvMRi6mC7CzX/ZmeomwhAARPqzwhzCO9S59O1RXX+mZYMVppiXo9qCjzoT9/lrdBtkvgbZ4iK5hk7H0oUPZQOuavaiK9kVoGPxGRoRq/vHwErhnid+qXiOBU66JWkQvcqUrlwcMv3DqyeycO1k2EU29ktEbW5veTnfA09k2Gnzd0ibFLssL0TsCFDxohkXUOAubUR3plER6enYZGIr2EwoOPhspb5JLmT1oRHbCCGw9caX1psHxJugJioN2BapW7R/KpWWkUHjvJXHBNEJ9B7Ve93fgSpJmeofgPT5i02MKWw6ThMA+EUeNz/3c17pv,iv:xUfT1bzlkayYkUMXU+maXx3jLYCKRrCvMGHFagTafL0=,tag:LGQoZ/UqoQltxFCp2yJo6Q==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNjVCUWFMWDR5QjZCZG96
            TTR6TVp2M1N3TTY0R2FRM0traTcxOUoyN21zClMwcFExZndMVXZRaWY5WXcra2k1
            YUdkQTJTdVNERDFXbmEra21YNlJ5TzAKLS0tIDFaVk9MekQ4SkFWMzlUaTBBY1pY
            ajVmVmZqdXlvWDVYYXVxeHBYTlZZWkkKghESoghPozvHb+H+27Dveu28zDbE6BIV
            KuUNCxSzgeNc9tows/29DpF/sOeR9aOie/FLOEkLcrJK5IzsELApyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T18:58:51Z"
    mac: ENC[AES256_GCM,data:GD+PotszqO/oH69+hwjOrBVuBnpyAptaBMlFGo0PkX8WQ+OBK8ag0gj1W3LFbQfnKmUMTObZbUPM2iQB+omMtP/H2bfaJDc1ME81yr7MHdaVIF1hZDRGtzKbX4neKA6n2z4VmyGhedUJRo8Jq18wXVUf2jPWXIyg9FvsW8YfJyA=,iv:IY4SWM22Z/9pfnHCSxtjRZPNMHyLiABslZZiNxPVBnk=,tag:zgGZ1A/oe32CXOqVCWe38g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
