apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: alertmanager-discord
    namespace: prometheus
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:icwULQ9UPmxFTT8ogasp5gObwDzkaznJ0eRfIDalTXnbGtmEO4nAgxN8/c5Uk+yVvYLpd9tiEB2JWafP0+8JQD7pZAcfGpJ6MRHROxayDQ73IDVtrU3ppkmenZ1Y5FCm+8ZpabomWcczH6CGvZE3TqetLwIGxrIMUgFwoMKmofc/WVx/psBLBtNniPFuKKJC0JmMgvNPJQb2KfhFiptsHKno3zwrihoh/JhRS/VPs5mTyj+CfHYRCSyrlqCnmZDcGp8Cg9UbhQDXlmqphAgJDx8jrXQ9hVyoW+RoKhaTt1K/hUoboBTXk5f1s5ngIZcPCrEbm863YKuyFzlNXP+Kmeu9HaNKu8ZaSrZkNFrbEhYg724YYSOJ01mjL41MaF4ZfF5oq4+PIc2exc4cfLCOBEAUg9ErCglyPqwCw6bMXA1XV2SK30iQTU1K7nOLteKO4+VS7h0qLxNrne0tWeih/FMyVrJ97jwLAAaRXGGcG2vyGO6j43SeGtmAY4ibiNZ7cHCUpuVjm9tm/bkwY/lG3iVHHZNqpxU2H94tBuHhESysuHlFJsV0BsFS1m/go0zVPrW+svq5I60p6uAP+uMxplPFrukpzkT4fOPCQQVw8mIDlEQ89SMx3BskECIPAYjgAs8IG+ZY3hdzekCaluMmxhPkiIWP/GsOIUXTXEBpgWwJbPcc25Rn1LeXoe+VXyxPHPFDxkd4pf06lvmZgnW+MG3N6VgxMG04n1FohHBBc0ATH8bd/ui4ahqSn4H71JtaAfTYe8aFWI6C395BkQSHSM0gl++OSbnDkHmORJGzAzq7xpKPEKJPnIaYaIf7uBx8aZpWh6Ydg5JzlSFKIK7R97MrahbpnRYxARGmp64dlothIdZxnc6PCVj0nLD/Mu2GT4L87C4ju5XqsMwlLKfYl/NkdfdAoS5bqoodFrwno9f+XwrPQOBjyiu3/9EuPZmvuodZnvSbHVGlzxsl8w38jeAnAU2LTlUcyx5msq8r+ze8MjBiXX/jKJJVvL2v48QOuv6O/wkZTzP1Y94XRPmncRy11aXLXnNu8CDcbfyMJlWse39N2MLIBWUCSs63D/Sv0wdaWg7I7Mf4tUxgL29OItFik0bKTXhEIQaLczHBGYKDoNTugyDvoTr5W6sIHdxuPpp5JgkLpbm/LTS37t4zN79sAkNl1ClEzFJTnsU33VTTiOM4OjDHzaRReF4o,iv:d59uUyFZ4nIRz+5+38g67dIbz+Oiwe1BXzjlqtSGtfs=,tag:AvnGYkxrc/R5IsuOn0rCZQ==,type:str]
sops:
    age:
        - recipient: age14r59mmdatjfp34tpv29p729r6xusyny2l8wzqpa8l2t3f7nltp0qq27axt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNjVCUWFMWDR5QjZCZG96
            TTR6TVp2M1N3TTY0R2FRM0traTcxOUoyN21zClMwcFExZndMVXZRaWY5WXcra2k1
            YUdkQTJTdVNERDFXbmEra21YNlJ5TzAKLS0tIDFaVk9MekQ4SkFWMzlUaTBBY1pY
            ajVmVmZqdXlvWDVYYXVxeHBYTlZZWkkKghESoghPozvHb+H+27Dveu28zDbE6BIV
            KuUNCxSzgeNc9tows/29DpF/sOeR9aOie/FLOEkLcrJK5IzsELApyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T02:20:26Z"
    mac: ENC[AES256_GCM,data:BhXZKnoq+QZ46fFfkCIfsHxkWIUZ7TUyrCwb8196PuQTyOS6i0p+r5XWcL3fBLB8XQW5Ouyoti3mAFprkEYsXLqJCHYZE/rVbasW+X7klCW0/jk5UZsGt14173m8ysW8i8gS8tj+9TUclJ8s+OcXqkNhlvv2zB1NkrUK2xe6Smk=,iv:mNuO3YArHOOjMBRD/X0OKS/5Qwec3cboTSLRHb1u66Q=,tag:S8RT83NWoKALTpteQllDNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
