apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus
resources:
  - namespace.yaml
  - helm.yaml
  - ingress-grafana.yaml
  - ingress-prometheus.yaml
  - grafana-dashboard-prox0.yaml
  - grafana-dashboard-k3s-hosts.yaml
  - prometheusrule-host-temps.yaml
  - prometheusrule-k3s-overrides.yaml
  - ingress-alertmanager.yaml
  - alertmanager-discord-secret.sops.yaml
