apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: twingate-secret
    namespace: twingate
data:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:CJRubuFZzhAFSBnzNdvUF4prPAqCF+1ZT62KdwOaYSbSjRtPhyLm9jmDLgmWnB2op13q7jMGTIqKPzy+/hEHhaJWoZXRixX9NREJ5m/p4nikoyWBPyuLiQxUk7kFKMgAZ4rYBgm47Lp3RI6+YDqBVhgXBt6W1UpiJhdQ7MyxFeBkKAay+e/3uL2oskoZfRSXzDOyKWYp3vAoQMZ6mi3UZeYkC2tNiEX3b3DEICxxm72kVOYSvl052Eik42Vl331RR1kkc7iwxgjZwjM598klmzq6Wu4CCInkRPExs2V5gG6ac908AQspv6pmDQ72Bs1c5YLW4VG1lK+DIFge6zpQCmQOvaZhqdJxSSLdwdItbulxJ6FlB6g5qeRe2bGL0PPkk4TXYPOjwnasad03yoneZtpcjFehH19SJdZaoqT48ZQs6e3h/VrWNbWY4qKLDim9I8pW7uNMwfzyBaqSTDjo82/hNobGjBNGrInJfvLcYZMKySXrcbdc3rUQaN9AJUYKvSMM9IaIT4w+0eM35mt/Ytywe2NbWrk0busIdn1YJazyrM/5mMuS8FuqcZT398DStJmy3YB8dQHBUbfxNKVJpgEn7yE3DmzTouTiNs72Y4IuQIPq06AKjQBXq5EBhmBLt0IRkcaBAnkRLvBtsUcu2ioedm1K5zDxjkYQeMI2MQpnj91DCgTmSl7RU42BQTStsasKGOWX/kV7ltMh/Oh19HzOx5yPM0fE/7JGTfq5CcYHMOLcQxMw52iZre8SJp4drtzG5R1i8c9fCpkVYeNvZJvU7ephVKmRln8fT6UsWEjftfFZYTeNkhol6YjXzi2zSEHHuv9A8Yr+0iUK,iv:HEKtLr1cRvIYRRYq1IgiCo24BXxOAgeB3VuT1rdG52U=,tag:mS9spz/YKg6wU3GkvT+gqQ==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:gE21S010uwycZNPViOMrSBRfIOpoDpW/2Cwy/f+b23y9IWreh27kj9MkFvlzDyyZ+YQHxCB8T5fRUzeqUgeQUEqBtT3MrkKyA4kAxlFf2ynUSRcpFavPPT3MWSXamBdpksK10NNDo2j3eZpjI6L2+ccAsAHawBUSxoJzAN7CuQRaHzT2MU5TvZSXNFGlwisKoQJmQddECBl88Mril3TJZ8BwM9M5dtraPTIP9898cgkpd2RW,iv:Bs/nu1jwzYF2O1tgnJOzexzBHeqCwvZkaZQEGoT12C8=,tag:1RTqxAkdVEGbY/Wie8Aatw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-22T05:01:44Z"
    mac: ENC[AES256_GCM,data:kFJhd7/FD6pxc1eruePjc7A3z5YXRa13dbYGJeNmd1Zj1pMZKremP+pUSmGNMObPNiG1PjTXTNG5tQxzo8544jcarCppLQ6sT9Y9I5kBVCVsIolzwvQuSskfMhKojgc+RT7oZYIwLNFvjPyh26OfPnrjM8jRwmXVPYj1OxFkrUw=,iv:cSyfCuxf8gj+y1dWT4GE6C7zwAdvk4NOssbO/tY0fZs=,tag:+NKKSY8mxYUlKUO04Pg8Pw==,type:str]
    pgp:
        - created_at: "2024-01-22T05:01:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzSN9uM2UoaDAQ//Tc22VjuYlL1ZYtdrDn3gqQRsgv02Zh/FC/RoJ9k2WbBL
            S39uK2uYKJ3xx34eWttiO2At9Kqvk4NCTyvLy+rC43kEVWjNQCmPT8i0CIEyHFy9
            gvRjRQi730gTgstjUwqvDeAjSk32s7Mypk6mOF1R9cBvf7DNODk28BgPtFAu6GcY
            wRVHZfzApcrfkfQHDQT1qc2G9/5JmxB/YzR/gL3At/ZQL/J4rx0Td6FFED+n72gy
            i25KK+X1hQWaHvzpVxoaIJpLTkqPSuTJ/pByyU4ADiMKb5FKK/KzATivRWV0lIXI
            vYbRKpjX5TS8Nmv9HXLjxfZFkGyILlyGF05fZVxwm/zMLDTslIQ0ttbHgiCjdgHf
            p5dDEIT4Iz/kc1JKl/hKLucZjY6Igt26ahn+3TN9Q/MATCTlNBQNXGCJMA1tCNYw
            gGgdFZENMWBgXtFgRKt1tiRPiHWIstOOwdm0XzN1/lKYYWDgwZRuhAJ2cbeEN+QN
            Y1tGqMLVBnt8U1ZbhXpxQAE7VMcZJkDRye019KFV5ut+Imi6HJ8au9Zi9cmnJi6D
            NCicw5ZTBnjEisVue2Xzyy2xvhVG10o8ta9cRRRH2U5Oba1QHwXcYofovibUwi29
            uuYJLMDszVREu7LARV61ifQi4MttPcUprvaNRYkOPbBoqz9ATDwReiu9i+wFaf/U
            aAEJAhDkTpTjq5qJqq6vmi8ViCLifK4RT+VTQpi2sOmGxN7UnQdhHuvL6Vv8lMrM
            SWnLV9BfA954PzoLjxzY3DzQcaq5MP7VWDNpHeRT18e+PuI1jOz9uvVszIUQ8vMG
            MwpnT4mJ0A6n
            =gSda
            -----END PGP MESSAGE-----
          fp: 77B66B06D2E06C5E776F4F92C7314867B986373D
    encrypted_regex: ^(data|stringData|email)$
    version: 3.8.0
