---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml  # scaled to 0
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

components:
  - ../0-components/health-checks
  # - ../0-components/security-context

patches:
  - target:
      kind: Deployment
      name: overseerr
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: overseerr
      spec:
        replicas: 0
        template:
          spec:
            containers:
              - name: overseerr
                startupProbe:
                  httpGet:
                    port: 5055
                livenessProbe:
                  httpGet:
                    port: 5055
                readinessProbe:
                  httpGet:
                    port: 5055
  - target:
      kind: StatefulSet
      name: overseerr
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: overseerr
      spec:
        template:
          spec:
            containers:
              - name: overseerr
                startupProbe:
                  httpGet:
                    port: 5055
                livenessProbe:
                  httpGet:
                    port: 5055
                readinessProbe:
                  httpGet:
                    port: 5055

labels:
  - pairs:
      app: overseerr
    includeSelectors: true
