---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-configs
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
