---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overseerr
  namespace: home
  labels:
    app: overseerr
spec:
  serviceName: overseerr
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      name: overseerr
      namespace: home
      labels:
        app: overseerr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: overseerr
          image: lscr.io/linuxserver/overseerr:1.34.0
          ports:
            - containerPort: 5055
              name: overseerr-port
          envFrom:
            - configMapRef:
                name: common-configs
          resources:
            requests:
              memory: "200Mi"
              cpu: "150m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - name: overseerr-configs
              mountPath: /config
  volumeClaimTemplates:
    - metadata:
        name: overseerr-configs
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 100Mi
